### ISSUE TITLE
Add notes in transcription interfact

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#106]

**Comment by cubap** [comment]
partially fixed in #101 branch. The _tpen_note property is available to the saving and a div.notes is in each transcriptlet now.

**Comment by thehabes** [comment]
Also see #127

**Comment by cubap** [comment]
@thehabes I assigned you so you can confirm that the saving action is working as you expect and then close this down. Every .transcriptlet has a textarea.notes now so the values are readily available.

**Comment by thehabes** [comment]
Need to make sure this field is there for initial annotation creation, update and export.  Also need to make sure this field is accounted for in JSONLDExport when lines are converted to mongo and saved in the store for legacy projects.  Make sure this is connected with the auto save timer so when a user is typing a note, it knows to auto update after 2 seconds of inactivity (put the same time trigger on .notes).  If this is all connected, then we're done.  I am in testing phase.

**Comment by thehabes** [comment]
Also, update lines in annotation store to support this.  A backup was made before this procedure was performed.
