### ISSUE TITLE
Archive IPR agreements 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#109]
Archive IPR agreements to be accepted on first load are not checked for restricted manuscripts and manuscript controllers

**Comment by thehabes** [comment]
This is tracked in the ipr table in mySQL.  This table needs to be returned in GetProjectTPENServlet for the current user's entries (so not the whole table, just the bits for this user).  The check is against archive name, which is also not in the return from GetProjectTPENServlet.  

To get archive into the return of GetProjectTPENServlet, we need to go into the canvas object and build the return for archive in the JSON object of a canvas, then track each archive in GetProjectTPENServlet.  For each archive name, check against the ipr table for the current user.  We can then connect canvas to archive to ipr to a user and have the client side check to make sure the user has accepted the IPR.  

How bad do we need this?  There is a fair bit of work involved with this.

**Comment by thehabes** [comment]
I have made a json array called ipr_agreement that comes back in the return.  There each object contains the folioNumber, the archiveName and the boolean for whether or not the user has accepted it.

**Comment by thehabes** [comment]
Final testing phase

**Comment by cubap** [comment]
I think you are over-complicating this. We are already checking for flags
to show the "restricted manuscript" popup and there are other uses for this
same mechanism (like the archive note). The back-end should check for this
when the project is requested (almost exactly like is done in the jsp), not
the front-end and just throw a flag if there is a problem. We don't need to
know if the user has accepted the agreement, only if there is one that is
not accepted. There are a ton of times there will be no agreement (imported
manifests, private uploads...) and we shouldn't have the front-end checking
for a problem that is unlikely to be there and which is a breaking problem
(meaning that the manifest shouldn't return at all if the IPR agreement to
use it is not satisfied).

**Comment by thehabes** [comment]
The folio object now has its archive and the back end does the work to check whether or not to pass the flag forward as to whether the user has accepted the agreement (or needs to accept the agreement) or not.  The acceptIPR() functionality has been restored and hits an API that uses the same code from transcription.jsp to get the job done.  So far, tests are successful.

**Comment by cubap** [comment]
That's perfect. 

Be thinking about a message system/error management that we will need for TPEN3 as you work through these. I think much of it can be generalized, but we will need to provide a very clear API for the RERUM feedback process when authorization or access fails somehow. These messages need to move around with all the annotations/objects and ultimately be both machine understandable (some standard) and human readable up to an interface.
