### ISSUE TITLE
#saveReport 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#110]
•	#saveReport floating button on saving messages, #saveReport with the past save times

**Comment by thehabes** [comment]
This area specifically handles changes on the text within transcriptlet textareas.  We would like to fire this on updateLine(), but updateLine() doesn't check for whether or not there has been a change.  The save report should only be populated when there has been a change. It should flash "No Change Made" for this case, else something like Column:A Line:10 saved at 15:11:07

**Comment by cubap** [comment]
The report says "No Changes" when the notes are saved successfully.

**Comment by thehabes** [comment]
sorry about that, didn't do the same "has there been a change" logic on the notes field, so it only checked against the transcription text field.
