### ISSUE TITLE
transcription and parsing history

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#114]
•	transcription and parsing history (this might be a big one) week

annotation store and interface work to be done

**Comment by cubap** [comment]
There is no #historySplit extant in the current transcription.html, fwiw.

**Comment by thehabes** [comment]
This still needs to be brought over from T-PEN classic, but should be fairly painless with the database rollback.

**Comment by thehabes** [comment]
Look to old code on trascription.jsp.  Watch out for history pertaining to deleted and merged lines, see if that can be made better.  The only way to go line by line to look at it is to click Next/Prev line in the transcription interface, see if this can be optimized and made separate with navigation options in the split piece.
