### ISSUE TITLE
automatic parsing - evaluate existing code

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#115]

**Comment by thehabes** [comment]
This should be back to normal with the database rollback

**Comment by thehabes** [comment]
Existing Code has proven successful.

If no lines are found on an existing canvas when a project is loaded, the automatic parser runs and places lines on to the canvas for a user.  This means a user never actually sees an empty canvas.  If they delete all their lines, the automatic parser draws new ones.  This means when a canvas is called from a newly created or copied project, the user will see the automatic parser lines.  

What does not exist is the option to turn this off and the option to choose not to keep the lines, but I am not sure this ticket is concerned with that.
