### ISSUE TITLE
XML Tag is not the full tag

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#123]
When the XML tags come in with the project, we need two pieces of information, the `label` and the `full tag` like `"segment"` and `"<seg type='seg' n=''>"` for example. This is missing in current 2.8 entirely.

**Comment by cubap** [comment]
related to #101 branch

**Comment by thehabes** [comment]
I will get a lil more detail on this from you today

**Comment by thehabes** [comment]
Just about finished with this, testing now.
