### ISSUE TITLE
Add "Page Controls" to the project.jsp Options tab

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#132]

**Comment by thehabes** [comment]
This option will be "all or nothing" for a small combination of tools.  The option for this depends on #130.  What will "page controls" options entail?  Is that [Line Controls] [Magnify] and [image Tools] or some other set?

**Comment by thehabes** [comment]
In the parsing interface, [page tool], [inspect[, [xml tags] and [characters] all show not matter what.  There is no option to turn them off for your project on project.jsp.  We would like getProjectTPENServlet to be able to include these in the list of tools it passes to the client so they can be toggled on and off.
