### ISSUE TITLE
Line Control should show #s by default, but not Lines

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#141]
should hiding the lines leave the ability to click to navigate? I think it should... but I'm not convinced.

**Comment by thehabes** [comment]
It sucks to have to click "Next Line" a bunch of times to get towards the bottom of the image.  I think we should leave it available.  It's way more obvious what's happening when the lines are visible and clicked, but I don't think making them disappear should get rid of the "click to navigate to that part of the image" functionality.

**Note
We do have some precedence for this.  This same functionality is present in the full view split.  When you click on the image in the right column, it will automatically navigate to that line in the transcription interface in the left column, and the visibility of lines does not affect the ability to "click to navigate".

**Comment by cubap** [comment]
That's just what I was thinking. Look at the side-by-side #158 and I think the lines obscure or "busy-up" the image too much. Using 28, I accidentally navigated with a stray click (upsetting because without animation from line to line, I wasn't sure what had happened) more often than I would like, but I like the idea of just clicking to get to your place. The splitscreen is perhaps too buried, but maybe 3.0 has a secret middle way we can find.

I did put in the skins branch an opacity reduction on inactive boxes so it isn't as obtrusive and that helped me a bit, if it doesn't bother anyone else.

**Comment by cubap** [comment]
I think the ultimate secret will be in the bottom image, which has a ton of real estate, but not much content value—it just fills the rest of the screen and makes the user more comfortable. There may be space for thumbnails or a minimap or something for navigation within and outside the folios.
