### ISSUE TITLE
Reconfigure Parsing Tool

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#145]
Donal will add comps. Icon bar, Legend, modal help with details.

**Comment by Domhnall101** [comment]
![screen shot 2016-12-15 at 10 22 28 am](https://cloud.githubusercontent.com/assets/17204541/21235436/5f19cd2a-c2bc-11e6-99a4-d0410115aadf.png)

**Comment by Domhnall101** [comment]
![61739e26-c2b1-11e6-97c8-ac322e009109](https://cloud.githubusercontent.com/assets/17204541/21235503/a660fe92-c2bc-11e6-8a40-4838eaa0b9d8.jpg)

**Comment by cubap** [comment]
@Domhnall101 under "Adjust Column", you have the copy "New column dimensions will overwrite some custom line settings" What does this mean?

**Comment by cubap** [comment]
Icons are needed. They should sit on a white box 30x30px. The black border will be added as CSS. Consider looking at Font Awesome for style compatibility.

**Comment by cubap** [comment]
scaling makes it a little more clear at magnification, but maybe not at 100%.
Thoughts?

Every other:
![image](https://cloud.githubusercontent.com/assets/1119165/21324860/211ddfb8-c5e9-11e6-9dbb-4b30627f98c1.png)

200%
![image](https://cloud.githubusercontent.com/assets/1119165/21324888/44790532-c5e9-11e6-8ca6-c874765d6ff8.png)

**Comment by cubap** [comment]
Now that I think about it, there isn't the pixel information to scale up, so the fact that you can see it on magnification is probably a red herring.

**Comment by Domhnall101** [comment]
30 px icons
for tool buttons
![mergeline30px](https://cloud.githubusercontent.com/assets/17204541/21326854/1d763adc-c5f2-11e6-83ae-136ea4c6762d.png)
![creteline30px](https://cloud.githubusercontent.com/assets/17204541/21326856/1d7b4874-c5f2-11e6-81a5-33bbd9bc9bf0.png)
![editline30px](https://cloud.githubusercontent.com/assets/17204541/21326855/1d78219e-c5f2-11e6-81a1-ae961ba815f6.png)
![deleteline30px](https://cloud.githubusercontent.com/assets/17204541/21326858/1d7f5d4c-c5f2-11e6-8cda-5e058a0e7437.png)
![editcolumnn30px](https://cloud.githubusercontent.com/assets/17204541/21326860/1d824ae8-c5f2-11e6-8b0a-e35959dc74b9.png)
![createcolumn30px](https://cloud.githubusercontent.com/assets/17204541/21326857/1d7c2b4a-c5f2-11e6-92d0-d01150971719.png)
![deletecolumn30px](https://cloud.githubusercontent.com/assets/17204541/21326861/1d83edda-c5f2-11e6-9619-6aecd58841ce.png)
![reparse30px](https://cloud.githubusercontent.com/assets/17204541/21326859/1d814756-c5f2-11e6-95b8-f021b1544a09.png)

**Comment by Domhnall101** [comment]
60 pixel icons fro tool bar
![createcolumn60px](https://cloud.githubusercontent.com/assets/17204541/21326887/39983738-c5f2-11e6-9275-a542453a01c8.png)
![createline60px](https://cloud.githubusercontent.com/assets/17204541/21326891/39a2cef0-c5f2-11e6-9a4d-71a11343b588.png)
![deletecolumn60px](https://cloud.githubusercontent.com/assets/17204541/21326892/39a320e4-c5f2-11e6-8a11-81e2e61092b6.png)
![deleteline60px](https://cloud.githubusercontent.com/assets/17204541/21326889/39a0ddca-c5f2-11e6-865c-808af65df257.png)
![editcolumn60px](https://cloud.githubusercontent.com/assets/17204541/21326888/39a02a7e-c5f2-11e6-8c66-b63d085dba4a.png)
![editline60px](https://cloud.githubusercontent.com/assets/17204541/21326890/39a12dc0-c5f2-11e6-8d55-64a450a34787.png)
![mergeline60px](https://cloud.githubusercontent.com/assets/17204541/21326893/39aa2e02-c5f2-11e6-9907-96997f51eb0f.png)
![reparse60px](https://cloud.githubusercontent.com/assets/17204541/21326894/39ace9c6-c5f2-11e6-9e24-1971c2151dc9.png)

**Comment by cubap** [comment]
NB: Changes to comps

- move icons to right end of buttons
- 60px in toolbar above (reduced) and 30px on buttons

Functions of buttons

- Columns
    - Create - draw new column only (remove 'adjust' from current code)
    - Adjust - adjust existing only (separate from create)
    - Delete - same
    - Reparse - delete all lines and fire imageResize
- Lines
  - Add - same; split lines at a point within a column
  - Adjust - same (for now); right edge only
  - Merge - existing functionality but without removing the last line
  - Delete - *only* removing the last line; consider suppressing for now

Clicking any button or icon fires the action of that icon.

**Comment by Domhnall101** [comment]
![screen shot 2017-01-04 at 4 33 54 pm](https://cloud.githubusercontent.com/assets/17204541/21661922/59077b68-d29c-11e6-8534-7b74d0eacf51.png)
final parsing scheme


REVISED BUTONS TO COME

**Comment by Domhnall101** [comment]
60 x 60 px icons

![createline60px](https://cloud.githubusercontent.com/assets/17204541/21693856/2c150394-d348-11e6-98b4-127160da3784.png)
![mergeline60px](https://cloud.githubusercontent.com/assets/17204541/21693860/2c20dea8-d348-11e6-90a7-b3affbc66f24.png)
![editline60px](https://cloud.githubusercontent.com/assets/17204541/21693863/2c2af14a-d348-11e6-8af3-d5422abc5038.png)
![deleteline60px](https://cloud.githubusercontent.com/assets/17204541/21693861/2c224946-d348-11e6-98c1-46d49e85735e.png)
![createcolumn60px](https://cloud.githubusercontent.com/assets/17204541/21693859/2c201540-d348-11e6-88a9-c5dd114a9b81.png)
![editcolumn60px](https://cloud.githubusercontent.com/assets/17204541/21693857/2c1d71aa-d348-11e6-837d-85ca1f8fe436.png)
![deletecolumn60px](https://cloud.githubusercontent.com/assets/17204541/21693858/2c1f9a20-d348-11e6-88ac-efba8d83df0a.png)
![reparse60px](https://cloud.githubusercontent.com/assets/17204541/21693862/2c2ab19e-d348-11e6-8431-2977ef5fa240.png)

**Comment by Domhnall101** [comment]
30 x 30 px  icons

![createline30px](https://cloud.githubusercontent.com/assets/17204541/21693903/55a44c6a-d348-11e6-9a51-0992a8d90128.png)
![mergeline30px](https://cloud.githubusercontent.com/assets/17204541/21693905/55ae09f8-d348-11e6-8004-98985cea7665.png)
![editline30px](https://cloud.githubusercontent.com/assets/17204541/21693906/55ae799c-d348-11e6-9be6-0d51c6cbab39.png)
![deleteline30px](https://cloud.githubusercontent.com/assets/17204541/21693908/55af2ec8-d348-11e6-86b6-5c6a8a77342f.png)
![editcolumnn30px](https://cloud.githubusercontent.com/assets/17204541/21693907/55ae9ce2-d348-11e6-830d-751ce69f0439.png)
![createcolumn30px](https://cloud.githubusercontent.com/assets/17204541/21693909/55b495ca-d348-11e6-98c4-0322cae18a40.png)
![deletecolumn30px](https://cloud.githubusercontent.com/assets/17204541/21693904/55ad07c4-d348-11e6-926d-5ac469b75a97.png)
![reparse30px](https://cloud.githubusercontent.com/assets/17204541/21693910/55b6bd32-d348-11e6-8165-1698353f2d04.png)

**Comment by thehabes** [comment]
I have finished this and built the interface to the mock up provided.  See

http://165.134.241.141/TPENPARSE

for the changes.

**Comment by thehabes** [comment]
This is now up at TPEN28
http://165.134.241.141/TPEN28

**Comment by thehabes** [comment]
awaiting approval from team

**Comment by cubap** [comment]
issue finished, bugs may arise in testing.
