### ISSUE TITLE
Image in parsing interface should NOT be resizable

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#147]
The image can be resized which causes lines to shrink, and then does not resize properly.  We want to disable the ability to resize the left side column with the image in it and only resize the right side column with the controls.

**Comment by cubap** [comment]
resizable isn't necessarily the issue, it is the disproportionate resizing. If the aspect is locked (ie, set a height or width, but not both), the resizing can stay.

**Comment by thehabes** [comment]
Too much chasing the rabbit here.  There is a bigger problem with this in that we need to be using the height and width of #imgTop, not #transcriptionCanvas for the ratios to get this right.  It will resize appropriately when shrunk but not when expanded, due to not explicitly defining #imgTop's width, which we can't do because we don't track its ratio.  Using the ratio of the canvas on it is wrong.  Also, for images that are taller than longer, it fits the image as naturally high as it can and usually adjusting the width will not affect the height because of the space that is left.  This needs to be punted right now.

**Comment by thehabes** [comment]
see 147_parsingImg branch to see where I left it.  I hit a wall I couldn't get passed after a couple hours of trying.
