### ISSUE TITLE
skin for transcription

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#167]
[28.pdf](https://github.com/CenterForDigitalHumanities/TPEN28/files/642825/28.pdf)

**Comment by cubap** [comment]
![image](https://cloud.githubusercontent.com/assets/1119165/21064370/fb289576-be1f-11e6-9ab9-b93c2082af65.png)
Parsing Stuff (in progress)

![image](https://cloud.githubusercontent.com/assets/1119165/21064394/12b18298-be20-11e6-9b64-26f59b9fd3d2.png)
Complex Parsing with Zones (in progress)

![image](https://cloud.githubusercontent.com/assets/1119165/21064408/21fbc0b0-be20-11e6-89b1-7e5d25e9bcce.png)
Near final Page Tools and workspace layout

![image](https://cloud.githubusercontent.com/assets/1119165/21064444/6aba2db4-be20-11e6-99c0-8b5d47ff206c.png)
Final Fullscreen workspace comp

**Comment by Domhnall101** [comment]
![2v](https://cloud.githubusercontent.com/assets/17204541/21232484/61739e26-c2b1-11e6-97c8-ac322e009109.jpg)
![2](https://cloud.githubusercontent.com/assets/17204541/21232486/631f3172-c2b1-11e6-975c-0777a1b97237.jpg)

**Comment by cubap** [comment]
Special Characters will be "Junicode", serif since the sans-serif won't show them as they will appear in the text. The XML tags are probably not as important to match.

**Comment by cubap** [comment]
another question for @Domhnall101 

Some buttons are all caps and some are Title Cased. This is fine, but some like "prev" and "NEXT" don't match. Is there a style suggestion for making the choice?

**Comment by cubap** [comment]
Title Cap everything

**Comment by cubap** [comment]
- No "Open Tags" text
- kibosh tips
- #captions, #saveReport text at 100%
