### ISSUE TITLE
Admin assumption?

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#169]
Why is user made admin if parsing is allowed? This seems like it would have a really bad side effect if the user wasn't otherwise admin and tried to do admin things.

~~~~~~~
function activateUserTools(tools, permissions){
    var tools = tpen.project.userTools;
    if(tpen.user.isAdmin || $.inArray("parsing", tools) > -1 || permissions.allow_public_modify || permissions.allow_public_modify_line_parsing){
        $("#parsingBtn").show();
        tpen.user.isAdmin = true; // QUESTION: Why isAdmin if you can parse?
        var message = $('<span>This canvas has no lines. If you would like to create lines</span>'
            + '<span style="color: blue;" onclick="hideWorkspaceForParsing()">click here</span>.'
            + 'Otherwise, you can <span style="color: red;" onclick="$(\'#noLineWarning\').hide()">'
            + 'dismiss this message</span>.');
        $("#noLineConfirmation").empty();
        $("#noLineConfirmation").append(message);
    }
...
~~~~~~~~

**Comment by thehabes** [comment]
Yeah this is no good, a side effect of old things and getting that #parsingButton to show.  You can comment out that line entirely.

**Comment by thehabes** [comment]
And make sure it doesn't affect this, it's the only thing I see commenting that line getting in the way of.

function activateTool(tool){
	// TODO: Include other tools here.
    if(tool === "parsing"){
        if(tpen.user.isAdmin){
            $("#parsingBtn").click();
            tpen.screen.liveTool = "parsing";
        }
    }
}

Need to do a proper check of whether or not the user can parse, not just an admin check (transcribe.js line 850ish)

**Comment by thehabes** [comment]
This is used to automatically open a tool and is used by linesToScreen(lines, tool), where the tool is one of the parameters passed in.

**Comment by thehabes** [comment]
I have commented the admin line out and updated activateTool() to do a proper check for whether or not the tool can be activated.  I ignore whether or not the tool was in the list of userTools though, if they are querying the parsing interface on page load then they want to load into it regardless if they want to see the button or not.  The only check is for the permission to do so.  Testing now.

**Comment by thehabes** [comment]
This is a success.
