### ISSUE TITLE
Transcription skinning and UI

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#19]
The transcription.html is the only one that has not recieved skinning.  There may also be some UI tweaks to take out old hard coded information with the tools in the workspace.

**Comment by thehabes** [comment]
The major goal is to slim down the workspace as much as possible.  

We want to move the special characters, xml and Line Control areas by making them free floaty boxes which are toggled by buttons in the workspace.

**Comment by thehabes** [comment]
Make special characters and xml tags floaty boxes as well.

**Comment by thehabes** [comment]
What about having a control panel that works like a split screen and puts tools to the side?  This could buy space in the workspace and be a good design for an ever-growing expansion of tools.

**Comment by cubap** [comment]
in the #101 branch

**Comment by thehabes** [comment]
This was a reminder for early conversations.  The ideas mentioned here are complete and the redesign has been broken out into many tickets.  I am closing this as a duplicate.
