### ISSUE TITLE
preloading images/annotations on previous and next pages after a wait

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#190]

**Comment by thehabes** [comment]
https://perishablepress.com/3-ways-preload-images-css-javascript-ajax/

**Comment by thehabes** [comment]
Is there a preference to how we do this?  I will probably go with something very similar to javascript method 1, but it will write into the tpen object, which will hold the cached images.  If there is no image present for the canvas when it loads, then it will load like normal.  If there is a cached image present, I will use that ( much like we use `tpen.project.dereferencedLists[]` ) 

However, we could use the DOM with hidden elements or even CSS to preload.  However, I feel it is more native to our code to store these in the tpen object and preload with javascript.

**Comment by thehabes** [comment]
Should I use the imagecache table in the SQL (see ImageCache.java)
