### ISSUE TITLE
shrinks to icons when screen width is small enough in splitscreen

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#194]

**Comment by Domhnall101** [comment]
2.9 feature maybe 3.0

**Comment by cubap** [comment]
The logic for the header could just be borrowed here, either looking for not enough space or just using the header "severe" to add a class that drops the buttons to icons.
The easiest way to do that with icons is to make the text of the buttons a ::before and change content to "" on .severe
