### ISSUE TITLE
Pull out of the Annotation Store and use TPEN database completely

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#202]

**Comment by cubap** [comment]
Found 19 matches of ANNOTATION_SERVER_ADDR in 12 files.	
- Canvas.java	
-         URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 160:40]	
-         URL postUrlCopyAnno = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/batchSaveFromCopy.action");      [position 214:48]	
-         URL postUrlCopyAnno = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/batchSaveMetadataForm.action");      [position 263:48]	
- Constant.java	
-       public static String ANNOTATION_SERVER_ADDR = "http://165.134.241.141:80/annotationstore";      [position 22:28]	
-     //public static String ANNOTATION_SERVER_ADDR = "http://localhost:8080/annotationstore";      [position 24:28]	
- CopyProjWithAnnoServlet.java	
-          ////                            URL postUrlannoLs = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 104:70]	
-          ////                                        URL postGetAnnoByAID = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 201:85]	
-          ////                                        URL postUrlCopyAnno = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 230:84]	
-          ////                                    URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 263:72]	
- CopyProjectAndAnnos.java	
-                             URL postUrlannoLs = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 99:66]	
-                                 URL postUrlCopyAnno = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/batchSaveFromCopy.action");      [position 200:72]	
- CopyProjectForPracticerServlet.java	
-                             URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 96:60]	
- CreateProjectFromMSIDServlet.java	
-                         URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 119:56]	
- CreateProjectServlet.java	
-                         URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 179:56]	
- GetAnnotationByPropertiesServlet.java	
-         URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/getAnnotationByProperties.action");      [position 28:40]	
- SaveNewTransLineServlet.java	
-                 URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 42:48]	
- UpdateAnnoListServlet.java	
-             URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/updateAnnotation.action");      [position 32:44]	
- UpdateTransLineServlet.java	
-             URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "annotationstore/annotation/updateAnnotation");      [position 44:44]	
- Annotation.java	
-         URL postUrl = new URL(Constant.ANNOTATION_SERVER_ADDR + "/anno/saveNewAnnotation.action");      [position 334:40]

**Comment by cubap** [comment]
I'm starting in Canvas.java getAnnotationListsForProject(Integer projectID, String canvasID, Integer UID)

**Comment by thehabes** [comment]
Yep that should cover where all the changes need to happen.  Remember that the output of these should be JSON for TPEN28, but the original servlets from old TPEN can be used when in the TPEN 1.0 interface.  Some of these are new servlets written from old servlets that exist, some of them are the old servlets that have been re-wirtten entirely so the old code isn't there.  You should be able to find its equivalent in the old TPEN code, the name should be *roughly* the same.

**Comment by thehabes** [comment]
I will start with restoring the original create/copy project so it no longer creates annotationLists for the folios.  Basically, I need to point the servlets that call these to their parallel servlets in the old code and make sure to update the links in the interface if need be. 
createProjectServlet.java
createProjectFromMSIDServlet.java
copyProjectServlet.java (copyProjectForPracticerServlet)
copyProjectAndAnnos (copyProjectWithAnnoServlet)

**Comment by thehabes** [comment]
Got the create and copy tested and put into the interface.  Moving on to Canvas.java

**Comment by thehabes** [comment]
Working on saveNewLine stuff, will do updateLine stuff after.

**Comment by thehabes** [comment]
updateLine() functionality works in transcription.html.  You can add new text and comments.  updateLine() and saveNewLine() need testing through the parsing interface, and the math in the interfaces will need to be double checked with parsing.

**Comment by thehabes** [comment]
finishing up with removeLine().  It was connected to updateLine() and updating the cached dereferenced annotation resources.

**Comment by cubap** [comment]
As of right now, I've updated all the active branches to `master` and `Database-Rollback`

**Comment by thehabes** [comment]
So far, this appears to be working in its entirety.  Needs a good blanket test for confirmation
