### ISSUE TITLE
#SaveReport uses 0-indexed line numbers

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#213]
and maybe while you're in there it should be made `<small>` or reduced in `font-size` a bit.

**Comment by thehabes** [comment]
Fixed.  I went through and made collinenum (the attribute on the transcriptlets) 1 indexed like it always should have been.  The other attribute on transcriptlets, lineid, is 0 indexed.

I then went into all the places in the code that took the attribute collinenum and ++ it.  This way, the 0/1 index change works proper throughout.  

I have tested all the places (lineColIndicatorArea, saveReport, Transcription preview, export) that this change could have screwed up and didn't find any errors, I am calling it closed.
