### ISSUE TITLE
Ctrl + Alt while split

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#216]
If there are any split tools open, hitting ctrl + alt to hide the workspace and move the image works, but upon release the lines and columns are all messed up.  Must refresh the page to fix it.

**Comment by thehabes** [comment]
Sometimes, the workspace doesn't even come back (compare page)

**Comment by cubap** [comment]
I don't see this in the current version...

**Comment by cubap** [comment]
The change is that the #topImg with is set to fullheight, so split screen tools that otherwise set it need to be predicted and the value saved in a memory, like the Peek-Zoom does.
