### ISSUE TITLE
move workspace

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#22]
Moving the workspace is a little choppy/glitchy, even though it works.  We would like new icons for the handles.

**Comment by thehabes** [comment]
(tested with project 4080 logged in as han.yan)

**Comment by thehabes** [comment]
We are changing the size of DOM elements and accessing them on mousemove.  We may have to look deeper into this to optimize the animation...

        $("#imgTop").height(startImgTop + event.pageY - mousedownPosition);
        $("#imgBottom").css({
            "height": startImgBottomH - (event.pageY - mousedownPosition)
        })
        .find("img").css({
            "top"   : startImgBottom - (event.pageY - mousedownPosition)
        });
        $("#imgBottom .lineColIndicatorArea").css("top", startImgBottom - (event.pageY - mousedownPosition) + "px");
        $("#dragHelper").css({
            top :   event.pageY - 90,
            left:   event.pageX - 90
        });

**Comment by cubap** [comment]
the .noTransition class was in tpen.css and not the nb.css. This addition will fix a few places where the animation of the lines or images lags behind the rest of the page. Fixed some appearance things under the hood as well.
