### ISSUE TITLE
.transcriptlet indexing seems off

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#241]
The current transcriptlet seems to be the transcriptletBefore in updatePresentation(). I suspect an indexing issue, but I don't want to break everything when looking.

The symptom is the first line doesn't swap out the text like it ought to.

**Comment by thehabes** [comment]
I changed how the indexing worked because it made me angry that I tracked things that should be 1 indexed with a 0 indexed value.  I will have a look.
