### ISSUE TITLE
Previous line isn't visible when transcribing

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#248]
It seems to be the same set buffer above the active line (unless it is the top of the canvas) instead of trying to show the previous line. That line is very important for continuity of transcription and should be visible.

On the other side, instead of a fixed piece of the following line, it seems to be a percentage, which leads to funny things when there are tall lines:
![image](https://cloud.githubusercontent.com/assets/1119165/22054605/02a45d2e-dd1c-11e6-8b24-e8fb37434a32.png)

**Comment by thehabes** [comment]
For what area is visible in #imgTop, I do a calculation of the height based off the line you are on + the next line's height.  We can change which lines to do the math with to do current line + if(prevLine).  updatePresentation() must relocate based on current line and puts the (-)y position for #imgTop img and #imgBottom img to the current line linetop location with some buffer.  We can also make that if (prevLine) use that line's linetop instead.  Not too much and no new math.
