### ISSUE TITLE
Magnifying glass containment

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#25]
We should contain the magnifying glass in the split screen tools to that section.  Right now, if you go out of the bounding area, nothing appears in the glass, which is ok, but we should bind it to the area it is meant to work it.

**Comment by cubap** [comment]
I haven't looked at magnify yet, but instead of attaching the mousemove to document (which I assume is what you did) you can attach it to the split container, which means the glass will be left behind if you move off the container and its position will stop updating.
