### ISSUE TITLE
Page Tools "Lines"and "Labels" should be toggle buttons

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#251]
Not check boxes

![image](https://cloud.githubusercontent.com/assets/1119165/22054729/c4977812-dd1c-11e6-8bed-70531b78fe05.png)

**Comment by Domhnall101** [comment]
your right hide/show text  change combined with blue/blue-grey on/off state should be an elegant Sufficiency

**Comment by Domhnall101** [comment]
click on these buttons goes to red not to bluegrey. blue grey is on hover but should also be on click
