### ISSUE TITLE
"Next Page" appear on the last canvas of a manuscript

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#254]
Previous Page correctly disappears.

**Comment by thehabes** [comment]
I did some stuff  with indexes last week, I will take this one and make sure it wasn't something I did.  It probably was.

**Comment by cubap** [comment]
didn't fix, but it isn't happening anymore. Maybe IT was broken and repaired by @thehabes messing around external to this ticket?
