### ISSUE TITLE
Missing "Close Tool" button on History, Abbreviation, and all iFrame tools

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#255]
We might need a wrapper here...

**Comment by Domhnall101** [comment]
The close button also needs to be styled
currently:
![screen shot 2017-01-18 at 9 43 08 am](https://cloud.githubusercontent.com/assets/17204541/22070730/a246f33c-dd62-11e6-8fa0-67c6d26b192c.png)
Change to:
![screen shot 2017-01-18 at 9 43 46 am](https://cloud.githubusercontent.com/assets/17204541/22070745/b07e3d20-dd62-11e6-9bbe-a9c7a2d76ba7.png)
