### ISSUE TITLE
Inserting hotkey doesn't advance the cursor

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#257]
Expected behavior is:

`xx|xxx` --(click or shortcut key for "$")--> `xx$|xxx`, but we get `xx|$xxx`

**Comment by thehabes** [comment]
rawr.  It's an easy fix.  It is in insertAtCursor().  Need to add 1 to cursor position math.  If the same thing happens in tags, need to add length of tag to cursor position.  Make sure to do it for each browser support case.

**Comment by thehabes** [comment]
Step 1: Log into /TPEN28
Step 2; Load project 4080 (Tradamus Simple)
Step 3: Insert a character.  Make sure the cursor caret is immediately after the character, and that the character was placed where the caret initially was.  
Step 4: Insert an xml tag.  Make sure the cursor caret is immediately after the full xml tag, and that the character was placed where the caret initially was.  
Step 5: Highlight a word and insert an xml tag.  That word should be wrapped with the opening and closing tag, and the cursor caret should be immediately following the CLOSING tag.  

If the tag/characters are inputted to the correct spot and you see your cursor caret at the end of the insertion, this issue will have passed.

**Comment by thehabes** [comment]
Success in Step 3, Step 4, and Step 5.
