### ISSUE TITLE
XML Tag buttons don't seem to do anything

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#258]
But the formatting is wonky as well, so something is off.

**Comment by Domhnall101** [comment]
agreed the xml tags are jacked up. Also not converting to side by side drawers at all and The edit button needs to be outside the grey box of tags or characters AND Present for both charaxcter and tags. I will put in a ticket for it this morning
![screen shot 2017-01-18 at 9 46 05 am](https://cloud.githubusercontent.com/assets/17204541/22070821/f7407bec-dd62-11e6-9606-01c061aa2bbf.png)

**Comment by Domhnall101** [comment]
they work for me but it is hard to select some of them
