### ISSUE TITLE
No error messages if saving fails

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#259]
that I can detect

**Comment by thehabes** [comment]
Saving on anything?  Like on project.jsp when adding chars and tags and stuff?  Or parsing lines and columns?  WHERE @cubap WHERE!

**Comment by thehabes** [comment]
On transcription.html, like when you hit next line, prev line or timer update.  There is no notice of failure to save.

What is the intended functionality?
- If you are unauthorized, you are sent back to the log in screen (via ref param) 403
- 404 or 500 display to user trex head to force them to stop.

**Comment by thehabes** [comment]
This problem can be solved in its entirety in one spot for the transcription interface.  updateLine() is the only function called to when switching lines or for the timer update.  We can track errors in the call back of the ajax here.  I will prepare the trex head in the call back for failure.

**Comment by thehabes** [comment]
Here is where all the update calls in the transcription interface lead...

```javascript
if(updatePositions){
    $.post(url,params,function(){
        line.attr("hasError",null);
        markLineSaved(line);
        $("#parsingCover").hide();
                    // success
     })
      .fail(function(err){
          line.attr("hasError","Saving Failed "+err.status);
          throw err;
          $(".trexHead").show(); //i added this
        });
    }
    if(updateContent){
       $.post(url2,params2,function(){
            line.attr("hasError",null);
            markLineSaved(line);
            $("#parsingCover").hide();
                    // success
          })
          .fail(function(err){
                    line.attr("hasError","Saving Failed "+err.status);
                    throw err;
                    $(".trexHead").show(); //i added this
                });
            }

```

**Comment by thehabes** [comment]
Also designed a #genericIssue popover to go with the trexHead

**Comment by thehabes** [comment]
Testing procedure:
Step 1: Log in, and open any transcription project in a new tab.
Step 2: In the tab where you logged in, log out
Step 3: Cause a 403 failure.  Do this two ways
    -Type something in the textarea and wait for the timer update to fire (for 403)
   - Type something in the textarea and change lines (for 403)
This failure should redirect you to index.jsp where you can log in.  Upon logging in, the transcription interface should be restored

Step 4: Log back in on the tab where you keep doing this.
Step 5: Refresh the transcription.html page.
Step 6:  In the code itself, alter the update calls URLs to be incorrect.  This will cause a 500.  You should see the trex head and hitting OK should refresh the page.

If we have successful outcomes at Step 3 AND Step 6, this will have passed.

**Comment by thehabes** [comment]
Step 3 produced the log in and reload loop.
Step 6 threw the trex head error and refreshed the page by clicking "OK".
