### ISSUE TITLE
No warning for content deletion (project.jsp)

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#26]
Removing lines and columns happens without a warning and need for confirmation.

**Comment by thehabes** [comment]
This happened when getting to the parsing page from project.jsp, not using the parsing split screen module in transcription.html.

**Comment by thehabes** [comment]
When choosing to correct parsing on project.jsp, it takes the user into the transcription.jsp parsing tool.  If we let this happen, we need to make sure [Return to Transcribing] takes the user to transcription.html otherwise they will get to the old transcription interface.

The other choice is to make it possible to get into the transcription.html interface and call up the parsing interface there, and change the link to point to transcription.html instead of transcription.jsp.  

We need to make a choice.

**Comment by cubap** [comment]
Yes, definitely the second. However, it may wind up being less trouble to take the old parsing interface and drag it in, but that's another issue.
