### ISSUE TITLE
Header collides with itself on narrower screens

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#261]
![image](https://cloud.githubusercontent.com/assets/1119165/22055349/63b64a92-dd20-11e6-908e-87a5a6fab695.png)

**Comment by Domhnall101** [comment]
would it help to convert to a hamburger with the jump to page pulled out on smaller windows?

**Comment by thehabes** [comment]
Yes I have noticed this too.  You will have to put some kind of max width on each .trimSection to force the text to ... at some point.  

We could also do a width detection on .topTrim to change the schema (like to a hamburger).

**Comment by thehabes** [comment]
The jump and the help are the only things that absolutely have to stay, everything else can collapse.

**Comment by Domhnall101** [comment]
not quite ther
Still possible get overlap
see below
![screen shot 2017-01-25 at 9 31 59 am](https://cloud.githubusercontent.com/assets/17204541/22296923/4ea091fa-e2e1-11e6-8e4e-a32f0236262a.png)

![screen shot 2017-01-25 at 9 32 43 am](https://cloud.githubusercontent.com/assets/17204541/22296937/60e3371e-e2e1-11e6-9423-0680d4496f65.png)


also at narrowest size classic and chat both
![screen shot 2017-01-25 at 9 32 51 am](https://cloud.githubusercontent.com/assets/17204541/22296964/73ae0a72-e2e1-11e6-809d-7773689affbb.png)
 diappear

**Comment by cubap** [comment]
The narrowest is correct. The margins of overlap in the middle are curious... I'll have to discover what is causing the size calculations to be off to fix is, but I'll track it down.
