### ISSUE TITLE
Classic T-PEN's icon is a beer stein

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#263]
Maybe the quill or something from @Domhnall101 would be better?

**Comment by Domhnall101** [comment]
I am working on something

**Comment by thehabes** [comment]
I like the beer stein.

**Comment by cubap** [comment]
some options from existing images

![favicon__4_](https://cloud.githubusercontent.com/assets/1119165/22166395/6f586346-df26-11e6-943e-56887539a1c7.png)
![favicon__5_](https://cloud.githubusercontent.com/assets/1119165/22166396/6f58f8a6-df26-11e6-9cb4-013fa7002a4c.png)

**Comment by Domhnall101** [comment]
emailed to patrick
