### ISSUE TITLE
"Transcribing as" uses email

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#264]
when we have the Full Name available and it seems far more personable. It is possible `/geti` doesn't have this in it, but it could without much work, methinks.

**Comment by Domhnall101** [comment]
to save space this can be changed to 'User:'

**Comment by thehabes** [comment]
`/geti` does not have name.  However, I do have a nifty tpen.user object that has everything we need, we do not have to populate this field with the data from `/geti`, we can move it down the stack to `loadTranscription()` where I will have `tpen.user.fname` and `tpen.user.lname`

**Comment by thehabes** [comment]
Got it.  Here are some things.  
What should I do if it so happens I could not find a first name, last name, or both?
It looks strange to have the name appear as same font same color, especially with short names.  Can we do something to make the name a little different than "Transcribing as"?

![currentuser](https://cloud.githubusercontent.com/assets/3287006/22263271/7ef04646-e239-11e6-9870-5b948641ee55.png)

![currentuser](https://cloud.githubusercontent.com/assets/3287006/22263302/9df2b72c-e239-11e6-8b0a-6d3ab0a4b776.png)
