### ISSUE TITLE
There seems to always only be one transcribing person

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#266]
Maybe a change to our login process or something affected the count. We used to get a list of logged in users back.

![image](https://cloud.githubusercontent.com/assets/1119165/22055688/02cf54ba-dd22-11e6-845b-5a22c6d7c782.png)

**Comment by Domhnall101** [comment]
this has been this way for at least a year

**Comment by thehabes** [comment]
```javascript
user.User [] currentUsers = user.User.getLoggedInUsers();
int numberTranscribing = currentUsers.length;
String userCount = (numberTranscribing==1) ? "is 1 user" : "are "+numberTranscribing+" users";
```

user.User.getLoggedInUsers() is always returning 1.  We will have to look around this to determine what it considers to be a logged in user, and what happens to a user when they log in to make sure the logic matches.  Maybe getLoggedInUsers() always returns 1 for some cases.  User.java is where to start.

**Comment by Domhnall101** [comment]
investigate and report

**Comment by cubap** [comment]
lastActive used to update in heartbeat, so it probably is from the death of the heartbeat.
I'll get back into this later, but I think if we attach updateLastActive() to the saving and update, or at least to the login, it would start working again.

**Comment by Domhnall101** [comment]
Let's plan on hiding the statement untill it's fixed
