### ISSUE TITLE
Share bar on about page should be reduced

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#267]
Just facebook and youtube like on the landing page

![image](https://cloud.githubusercontent.com/assets/1119165/22055724/2fd68eb0-dd22-11e6-838c-e2dfd4297cee.png)

**Comment by Domhnall101** [comment]
not merged?

**Comment by Domhnall101** [comment]
not seeing the change
![screen shot 2017-01-25 at 9 17 56 am](https://cloud.githubusercontent.com/assets/17204541/22296268/396ec768-e2df-11e6-906b-3565888265d2.png)

**Comment by cubap** [comment]
It wasn't changed for admins (who have a slightly different about page). It is now.
