### ISSUE TITLE
Project Log is anemic

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#269]
Project 4080 has only 7 records and only goes back one day.

**Comment by thehabes** [comment]
Weird, I've got nothing off the top of my head for this one, I will have to investigate.

**Comment by Domhnall101** [comment]
investigate and report back

**Comment by cubap** [comment]
Okay, so here's my guess. I think the fork of the db left this one blank, but will be restored once the 28 is launched. I've spot tested the things we think should be going in and they all work.
