### ISSUE TITLE
Style close tool

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#272]
per image in #255

**Comment by Domhnall101** [comment]
![screen shot 2017-01-18 at 9 43 46 am](https://cloud.githubusercontent.com/assets/17204541/22071447/d2559842-dd64-11e6-9079-dc0eedbaec79.png)

**Comment by Domhnall101** [comment]
PAGE TOOL BUTTON HAS ARROW IN WRONG DIRECTION
