### ISSUE TITLE
Splitscreen - adjusting splitscreen width

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#281]
doesn't work on anything
MAC - Chrome

**Comment by thehabes** [comment]
*Notes for clarification

- you cannot adjust the width in parsing, the image is the maximum height and width it can be for best parsing results, so the user should not be allowed to resize.  This is why I tried to center the interface (this caused the window resizing issue in parsing).  I didn't necessarily intend for this to stay, but I threw it in there to see what you guys thought about that.  

- pageTools is a fixed width and intended to be so, there is no need to resize that either.

- Every other split screen SHOULD BE ABLE to resize and if they do not this is an error.
