### ISSUE TITLE
PARSING Window - Styling 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#286]
1. buttons at top need to go from drop shadows to bluegrey on hover and click. images should work unchanged.
2. selection of tools causes every tool box and text to become read and the red text becomes unreadable. This should only happen to destructive tools and the red text should go white.

**Comment by thehabes** [comment]
Page Tools remained selected when clicking close, although the toggle on the button itself works.  A commit has been put into master to fix this.

**Comment by thehabes** [comment]
Adjust Line and Merge Line carets are in a weird position when selected.  Also, the background here is blue like the body background.  The #parsingDiv that contains these tools has the wrong height or something like that.

**Comment by thehabes** [comment]
I think I did all the things I know about that pertain to this ticket, so I think its ready for review, but I don't know why it was put back into in progress initially.  Anyway, I have moved on.

**Comment by Domhnall101** [comment]
the only boxes to go red are
destroy column
reparse page
delete line
