### ISSUE TITLE
some active button colors are still red

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#292]
in page tools for sure, at least.

**Comment by thehabes** [comment]
I blame @thehabes

**Comment by thehabes** [comment]
Any button that is blue should have it.  The only ones that should not are characters and XMLs.  I need to track down the color.

**Comment by thehabes** [comment]
color is #8198AA

**Comment by Domhnall101** [comment]
this is still an issue with page tools split window -
