### ISSUE TITLE
preloadFolioImages() is presumptuous

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#298]
Uncaught TypeError: Cannot read property '0' of undefined
    at preloadFolioImages (transcribe.js:4346)
    at transcription.html?projectID=3586&p=13179440:2095

For large projects where there are many pages (this one has like 40), it takes 45-55 for getProjectTPENServlet to finish running, especially because 90% of the images don't actually resolve so the back end chokes.  preloadFolioImages() runs after 15 seconds, and fails because there is no tpen.manifest.sequences[0] in memory.

**a further problem, if the image failed to load and is sitting in this manifest, it will have a height and width of 0 at the canvas level.  preloadFolioImages() should check this and if it finds this case, the function should know that it should skip preloading this image because it WILL fail.

**Comment by thehabes** [comment]
*NOTE:
 This does not cause a page break or anything bad, just a console error.  However,  in a manifest that took a long time to be assembled, none of the images will be preloaded because it will not have been there for the URLs to be gathered when the function fired, so it is useless right now for some manifests, it should be fixed.

**Comment by cubap** [comment]
I would just initialize the timeOut in the onload for the first canvas image, since that is after the manifest is loaded.
