### ISSUE TITLE
Move icons to right side of buttons - page tool tab - styling

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#301]
these icons should be on the right in all locations

**Comment by thehabes** [comment]
Lined them up along the right side...see picture below

![right](https://cloud.githubusercontent.com/assets/3287006/22266647/749199c2-e246-11e6-9391-73b7bfb2736c.png)

**Comment by Domhnall101** [comment]
The icons needs to sit next to the text in the button
see samples beow
![screen shot 2017-01-25 at 9 24 17 am](https://cloud.githubusercontent.com/assets/17204541/22296544/1b715d24-e2e0-11e6-8fa7-639a241a2f93.png)
![screen shot 2017-01-25 at 9 24 09 am](https://cloud.githubusercontent.com/assets/17204541/22296545/1b716382-e2e0-11e6-994a-1dceb3af88d1.png)

**Comment by thehabes** [comment]
Moved them next to the text.  See image below...
![parsingui](https://cloud.githubusercontent.com/assets/3287006/22298093/ec523cc0-e2e4-11e6-96c8-0bd0995495d3.png)

**Comment by Domhnall101** [comment]
Changes not showing on mac side

**Comment by thehabes** [comment]
They are in the right place, but the pageTools split area is acting weird.  This one can close, but we will have to track that pageTools split area (on iMac) as a new issue.
