### ISSUE TITLE
View full page went away?

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#303]
Not sure when or why. Maybe because removing the transcription preview and relocating the click to navigate and inspect made it redundant with Compare?

At any rate, it is still in the DOM, but not in the project options, so it won't show up.

Thoughts?

**Comment by thehabes** [comment]
hmmmm i dont know what happened.  It was overlooked, and will not be available to users until it is included in the front-to-back schema like compare pages is.

**Comment by Domhnall101** [comment]
Patrick will explore the option of reinstating this as a split screen tool.

**Comment by cubap** [comment]
This is fixed, but it is just the image (with and inspect button)
Still missing is the click to navigate and transcription preview

**Comment by Domhnall101** [comment]
Image not loading on mac
