### ISSUE TITLE
Compare images splitscreen - Styling 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#305]
Center all the buttons - compare to, hide workspace, inspect

Change the compare to pull down to match the styling of the pull down on the main transcription tool bar.

**Comment by thehabes** [comment]
Most of this was already done when I got in there, I put the finishing touches on it for this issue.  See image below.
![compare](https://cloud.githubusercontent.com/assets/3287006/22265771/1326b904-e243-11e6-9347-7145131a8bc6.png)

**Comment by thehabes** [comment]
will be available by the 1/25 build.
