### ISSUE TITLE
Parsing split screen has non function expand triangles. -remove them and selection halos

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#307]
expand triangles do nothing at all as all copy is visible at all times. remove them

Selecting  any button produces a halo around the selected button the buttons already have a change on activation so remove these halos

**Comment by thehabes** [comment]
took out triangles.

**Comment by thehabes** [comment]
Got rid of halo, for reference see
http://stackoverflow.com/questions/9287803/removing-the-blue-glow-from-an-html-text-input-when-selected

**Comment by thehabes** [comment]
For the 1/25 build
