### ISSUE TITLE
Parsing window - deactivate option arrow

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#316]
option arrow screws up image in parsing window

**Comment by cubap** [comment]
@Domhnall101 What does this mean? Can I see a shot of a "screwed up image" or have more details about what an "option arrow" is, please?

**Comment by Domhnall101** [comment]
when I click -option arrow i get this (stupid action for me to do but I did it.
![screen shot 2017-01-26 at 10 12 17 am](https://cloud.githubusercontent.com/assets/17204541/22339561/0079a2a8-e3b0-11e6-9ac9-c23a084da271.png)
