### ISSUE TITLE
Return key causes page refresh and reset to top line 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#319]
do it and see

**Comment by thehabes** [comment]
yep, don't even need to be focused on anything in particular.

**Comment by cubap** [comment]
I bet there is a button somewhere without a proper type applied, so it is trying to submit a form that doesn't have an action which defaults to "" which means reload the current URL.

**Comment by cubap** [comment]
transcribe.js line 3559
`window.location.href=relocate` is "" which is bad.

**Comment by thehabes** [comment]
```javascript
 else if (event.which === 13 && (tpen.screen.liveTool !=="parsing")){ //enter
          if (event.shiftKey || event.altKey) return true;
                event.preventDefault();
                Linebreak.moveTextToNextBox();
                return nextTranscriptlet();
            }
```

moveTextToNextBox() calls `Data.saveTranscription("")` no matter what and triggers a page refresh.  I fixed Data.saveTranscription() so that it ignores any page relocating if the parameter to saveTranscription is falsey and took Data.saveTranscription() out of moveTextToNextBox().

**Comment by thehabes** [comment]
Why did this get moved back?  It is working.

**Comment by thehabes** [comment]
Make sure you are testing at http://165.134.241.141/TPEN/ and not http://165.134.241.141/TPEN28, the apache cache is still broken for that name.

**Comment by thehabes** [comment]
To get your images in http://165.134.241.141/TPEN/, you will have to be logged into http://165.134.241.141/TPEN28.
