### ISSUE TITLE
#captionsText does not display RTL correctly?

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#326]
putting direction or dir on the div does not change how the text is displayed.

**Comment by thehabes** [comment]
Now it does, but it does weird things with punctuation.  The width of the area does not span the width of the text area, so it ends up centered.  see image below. 

![11](https://cloud.githubusercontent.com/assets/3287006/22387325/b24ba242-e4a0-11e6-829f-ff01b5c41d11.png)

**Comment by cubap** [comment]
This is "correct". The roman letters in the middle are a block that flows LTR in a RTL context, but the "!" is neutral so it shows up where is is expected. Think of the sentence, "How do I say, 'Hello, Bryan!' in Hebrew?" The correct response would not be "!nayrB ,$#@", but "!Bryan ,$#@"

**Comment by Domhnall101** [comment]
this will be resolved with the dir=auto ticket hopefully
