### ISSUE TITLE
project.jsp XML Tags are not possible to select

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#332]
Even when RTL is not checked, I cannot save XML tags as a selected option.

**Comment by thehabes** [comment]
Make sure you are merged with master.  I fixed this before I left, I put the working version up at /TPEN, make sure you are on /TPEN/project.jsp, I think the links might take you to /TPEN28/project.jsp.  I just tested logged is as han.yan@valpo.edu on project 5441 and project 4080 with success.

**Comment by thehabes** [comment]
This was because of the addition of RTL to the project options, so i am tagging it as a RTL bug.  Test again, I  did so again today just to double check and could not replicate.
