### ISSUE TITLE
RTL use dir = auto in all the locations listed below

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#340]
These should be applied in all versions of the interface not just RTL. RTL should represent the rearranging of the interface.
1. import text
2. View Full page
3. HTML export
4. Check PDF export correct if needed
5. Check JSON export and report back
6. preview transcription
7. line history
8. notes

**Comment by thehabes** [comment]
This will need to be addressed in performInterfaceShift() and the CSS.  I will make a grouping on all elements I am setting direction="auto" too in one spot in the CSS and will not overwrite this with any interface shifts so that it always stays auto.  
If we are paranoid, we can have a setToAuto(); function that goes over each element and makes sure its CSS is auto in performInterfaceShift(), but that's probably overkill.

**Comment by thehabes** [comment]
```css
#fullText 
.previewText
.notes
.theText
#captionsText
.exportText
#contribution
```
Are the objects that take care of that list.  There is no CSS property for dir=auto, so we will have to write a function that finds all the objects and adds that attribute.  In transcription.html, this is performInterfaceShift() but on the jsp pages we may have to explicitly call the function on page load or attach dir="auto" to the html elements as their are built by the Java on the page, I will have to look at that. 


Unsure about PDF export.
The JSON output just needs direction assosiated with the objects to flag them as right to left.  I can do this in GetProjectTPENServlet.java by detecting that RTL is an active option and adding a parameter to me annotations lists and/or annotations from Transcription.java stating what direction they are.  The text should come out correctly as is.

**Comment by thehabes** [comment]
Pretty sure all areas that need dir=auto get it, I have tested, let me know if I missed any. See

```javascript
function setDirectionForElements(){
    $(" .previewText,\n\
        .notes,\n\
        .theText,\n\
        .exportText,\n\
        .exportFolioNumber,\n\
        .historyText, \n\
        #captionsText,\n\
        #contribution,\n\
        #trimTitle \n\
    ").attr("dir", "auto");
}
```

**Comment by Domhnall101** [comment]
looks like it is fixed every where but 
line history and preview transcription
