### ISSUE TITLE
TPEN28 OFFICIAL DEPLOYMENT

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#348]
I will first deploy this war file on our current prod server, so that it is available at t-pen.org/TPEN28 and have it point at db tpen28, not TPEN, so that we can test with no harm to any data.  
To accomplish this I will
 - Port the current db tpen28 that is on the dev server onto our current prod server.
 - All data CRUDing from testing will happen on this database, a safe and neutral location that we have permission from the government to blow up.  

Once this is complete, we need to do a blanket test of the functionality, just to be sure everything works in the prod environment like it works in the dev environment.  All of you data from all the previous testing you have done on the dev server will be there.

When we feel that this version is stable, we have two options right away
- Point it at db TPEN and rename the war TPEN.war, and we are live and public.
- Get this over onto our new prod server, and hopefully be able to deploy under the URL t-pen.org/TPEN

Once we have made the decision on the above, we have to figure out what we are doing with the TPEN data.
We have options.  We can either 
- get the dbs TPEN and tpen28 into the centralized database with ITS and point version.properties of TPEN to those
- make sure the new prod is set up with SQL and port the dbs TPEN and tpen28 over to the new prod.  
**In either case, we need to test against tpen28 first to make sure everything works before point at TPEN and going live because we are moving the db to a new location, so we need to test CRUDing.**  

Once we consider ourselves live, we have to make sure the URLing works like we want.  www.t-pen.org should point to the new TPEN28.  If we name the .war file TPEN.war, then that code will be deployed at t-pen.org/TPEN. Any explicit link to t-pen.org/TPEN/ would pull up the new version.  

**NOTE people who have bookmarks that point to anything /TPEN/transcription.jsp will automatically load up in "classic version".  Is this what we want?** 
**REMEMBER we allow switching to classic from within the TPEN28 transcription interface, but it doesn't point at the old version, it simply loads up transcription.jsp from within itself, which is the classic version of this interface.  Assuming the name /TPEN/ would therefore have no ill effect to this URLing.**
^^If we want to make changes to how this URLing works, we need to remember that it will change the functionality of these things, so a decision set in stone should be made.

That should cover us getting to completely prod ready, at which point we can go public.  Cheers!

**Comment by thehabes** [comment]
Someone should probably use the done column to test, so we can get the Done tickets to become Closed tickets.

**Comment by Domhnall101** [comment]
That's what the done is for. I will be using it to go through the final 2.8
live deployment

**Comment by thehabes** [comment]
I will post to this when it is up.

**Comment by thehabes** [comment]
Prod test deployment is available at http://www.t-pen.org/TPEN28/

**Comment by Domhnall101** [comment]
Which server is this on?

**Comment by Domhnall101** [comment]
By ehich I mean new server with tradamus or same old server with current
-pen

**Comment by thehabes** [comment]
Same old server as current T-PEN.  However, I now have a working version up on the new prod server.  This can be tested at
http://165.134.105.25/TPEN28/

**Comment by Domhnall101** [comment]
Atta boy!! I will try to try that out this evening

**Comment by thehabes** [comment]
They have independent databases, so things you do at http://165.134.105.25/TPEN28/ cannot be seen at t-pen.org/TPEN28, so stick with one when you are testing.  If you notice something does't work in one, try it on the other just to make sure its not the server.

**Comment by thehabes** [comment]
All testing should now be done at the deployment http://165.134.105.25/TPEN28

**Comment by thehabes** [comment]
T-PEN 2.8 is live at http://t-pen.org/TPEN (hosted from 241.71).  This is where testing should be done from now on.

We will work to transition to 105.25 again soon.

**Comment by thehabes** [comment]
TPEN ended up in its proper place on the prod server.  This is complete.
