### ISSUE TITLE
Adjust Columns

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#368]
If you have already clicked one of the buttons that turns the lines into columns in the parsing interface, there is no issue.

However, if adjust columns is the first thing you try to do, the lines do not change into columns and you cannot adjust them.

**Comment by thehabes** [comment]
Going from destroy columns or reparse page to adjust column did not switch out the functionality.

**Comment by Domhnall101** [comment]
adjust column works sideways but not up and down
