### ISSUE TITLE
Landing page sign in area needs adjusting

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#370]
reset password misplaced over input fields
Chrome on mac

![screen shot 2017-02-22 at 2 00 14 pm](https://cloud.githubusercontent.com/assets/17204541/23230767/c9282818-f90a-11e6-9a80-83513108833c.png)

**Comment by thehabes** [comment]
This is a mac and/or browser thing we need to look at.  Below is what it looks like on windows in Chrome and Firefox


![11](https://cloud.githubusercontent.com/assets/3287006/23231627/1d0fc686-f90e-11e6-9cec-260d050b0035.png)

**Comment by thehabes** [comment]
Added in some forced <br>'s, maybe that will help.

**Comment by cubap** [comment]
I bet this is the same as the notes button and the width is reporting wrongly. If the breaks don't fix it, we should try clearing.
