### ISSUE TITLE
Buttons not updated on options page under project managment

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#373]
I added two buttons and they don't show in transcription or on options page under project management.
the buttons that do appear in trancription appear on options page under project management but do not appear on the edit buttons page.
![screen shot 2017-02-22 at 2 35 24 pm](https://cloud.githubusercontent.com/assets/17204541/23231098/2b0d58fe-f90c-11e6-8b4a-fb4ecb0949c3.png)
![screen shot 2017-02-22 at 2 35 16 pm](https://cloud.githubusercontent.com/assets/17204541/23231100/2b1010b2-f90c-11e6-909e-975fb0afa4e0.png)
![screen shot 2017-02-22 at 2 35 00 pm](https://cloud.githubusercontent.com/assets/17204541/23231099/2b0e35c6-f90c-11e6-90de-f25a854dfa58.png)

**Comment by thehabes** [comment]
This seems to happen when there is a break in the button order, like when it goest (1,2,3,7).  It only shows 1-3, so buttons.jsp is caring way to much about the position value.
