### ISSUE TITLE
XML buttons not showing on options page under project managment

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#374]
they are not showing on options page under project managment
they do show on edit buttons and in transcription interface

**Comment by thehabes** [comment]
This is working on the projects I am testing, can you give me a project number its not working for?  See image below

![1](https://cloud.githubusercontent.com/assets/3287006/23232479/fffb46bc-f910-11e6-8a32-5adcb6482de5.png)
