### ISSUE TITLE
Previous Page

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#386]
The button shows up on transcription.html page load when loading the first folio.  When you change the page to the first folio from a different page, it works correctly (does not show up).

**Comment by cubap** [comment]
it's in scrubNav() I'll take a look

**Comment by thehabes** [comment]
scrubNav() works, but the function at the end of loadTranscription() was not firing.  I moved it further down the stack into the image load of loadTranscriptionCanvas(), we only need scrubNav() when that works.

**Comment by thehabes** [comment]
Works
