### ISSUE TITLE
RTL appears to be on by default?

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#387]
I created a new project and RTL was selected on the options.

**Comment by thehabes** [comment]
I created project off of MS Austin, TX, Harry Ransom Center BR 332 A83 1526, projectID 5454, and this did not happen.  I proceeded to make a couple more and could not replicate.

After digging I found this which is the only thing that could be possible doing this...

public static void initializeTools(int uid) throws SQLException {
      for (Tool.tools iter : tools.values()) {
         if (iter != tools.sciat && iter != tools.unknown) {
            Tool t = new Tool(iter, uid);
         }
      }
   }

I will adjust this function accordingly.
