### ISSUE TITLE
Manifest is 401 on public projects

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#395]
For public projects to work, the manifest has to be open to non-members (is doesn't have to be completely public, but it could be). At the moment `/project/4080` comes back 401 and other public projects are 500 on the transcription page (probably for the same reason). It works to see the images and even the canvases (hooray!), but not the manifests.

Once in RERUM, this is moot, since all GETs are open.

**Comment by thehabes** [comment]
This is because /manifest/PID is the one without the user restrictions.  /project/PID requires you to be logged in.  I will make it so that no matter what, user restrictions are ignored (This is ProjectServlet.java)

**Comment by thehabes** [comment]
Its a 500 now, server problems
