### ISSUE TITLE
Split area overflows parsing area when resizing the window

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#409]
sometimes, this one is tough to replicate on windows.

**Comment by thehabes** [comment]
I put this through quite a stress test on Chrome and Windows and could not replicate

**Comment by thehabes** [comment]
This seems OK on windows, but this error is still reported when using an iMac

**Comment by thehabes** [comment]
This is happening on Windows as well.  Project ID 5660 p 13224373.  #transcriptionCanvas become wider that #transcriptionTemplate.  #transcriptionTemplate is inline-block with #parsingSplit, but when the canvas' width goes beyond this, it makes it look like the parsing split is overflowing #transcriptionTemplate, but its actually just an optical illusion caused by #transcriptionCanvs

**Comment by thehabes** [comment]
get rid of background color on .centerInterface and make it max-width:100% , make #transcriptionCanvas max-width: 100%, then it works like it should

**Comment by thehabes** [comment]
I made the changes, but do not know of any projects in TPEN_TEST that have the break that I can test this with.  Donal, if you know of a projectID you have in the test data you can use to test this, it is up on /TPEN28/

**Comment by thehabes** [comment]
Tested on that same project Ramon had issues with (5660), confirmed fix on my machine and his machine.

**Comment by thehabes** [comment]
Has to do with the positioning of #parsingSplit inside .centerInterface with how we want it positioned next to #transcriptionTemplate.  Without some UI redesign, we are restricted to two choices (from code)

THIS WILL WORK (KEEPS IT RIGHT NEXT TO #transcriptionTemplate, but wide images cause the parsing controls to float off screen.  This may be what causes #409.  It was position:fixed, let's try position:absolute.  They cause the same functionality)
      position: absolute; /* position:fixed; */
      float: none;

      OR THIS WILL WORK (LOCKS THE PARSING CONTROLS TO FAR RIGHT OF SCREEN.  It causes a constant buffer between images that are taller than they are wide and the parsing controls.  However, this may fix #409 because the split area should never float over the image.)
      position:relative;
      float: right;

**Comment by thehabes** [comment]
it is great to test this against 5660 and 4080 (you should have parsing permissions) on /TPEN/ (when we put this version up).  It shows the complexity between the two situations, and what the consequences are of the choice we make for this.

**Comment by thehabes** [comment]
The float right, position relative version that fixes the parsing tools to the right side is implemented.  it helps with this and other issues, but for project 5660, our limits are meant to deal with an image that is taller than it is wide.  The 5660 is wider than it is tall, so when it hits the small limit and forgoes the parsing tools, it tries to resize larger based on its width and ends up off screen.  If we decide to stick with this fix, we will have to go in to where these limits are and see if we can fix this issue.

**Comment by thehabes** [comment]
well that is partially a lie.  This happens in the version without this fix as well.  It is because T-PEN expects images to be taller than they are wide.  This is not a breaking problem and most users will never experience it, but we do need to think about it.  It is a weakness of T-PEN to want images that are taller than they are wide.

**Comment by Domhnall101** [comment]
fix math
