### ISSUE TITLE
Adjust Column Issues

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#417]
Adjust columns not firing in parsing window.

**Comment by thehabes** [comment]
On Windows, you can see that it does not paginate. If you click return to transcribing your adjustment is not seen. However, if you refresh the page, the adjustments you have made are present, so we know it is at least saving just no redrawing correctly.

On Mac (in Chrome and Safari) it is worse. The update happens only intermittently, and of those intermittent updates only a subset of them actually update correctly. It feel a lot like the other problem we had where we had event handlers going on the columns and other things at the same time, but initial investigation suggests that is not the issue.

This may be two separate issue, and the Safari issue in general is part of an over all cross browser support issue.

**Comment by thehabes** [comment]
Working pagination first

**Comment by thehabes** [comment]
"@id" vs "tpen_line_id" problems.  Now I have made @id value = tpen_line_id for all objects so the code is not confused.  I bet this is what was causing update problems as well.

**Comment by thehabes** [comment]
Looks good!

**Comment by thehabes** [comment]
bottom/top adjustments are still screwy

**Comment by thehabes** [comment]
Looks good

**Comment by thehabes** [comment]
When I have a small (say two line) column and I adjust it to be larger from the bottom or top, this fails.  However, if I have a larger column (say 10 lines) that I resize from the top or bottom to make smaller, this works.

**Comment by thehabes** [comment]
Still having some wonky issues with this, I will have to go back at it tomorrow

**Comment by thehabes** [comment]
should have this resolved by lunch time

**Comment by thehabes** [comment]
Tested up, down, left, and right side resizing and both variations for each case (either increasing or decreasing the volume of the column) and all tests passed using Windows 8.1, Chrome logged in as han.yan@valpo.edu on projects 5330, 5497 and 5555 at t-pen.org/TPEN28/ .  This is now up for testing at /TPEN28/

When this development branch is approved, we need to push it to production before any other bug fix.

**Comment by Domhnall101** [comment]
This works but the merge lines is broken again .delete line is now working



On Wed, Mar 15, 2017 at 11:36 AM, Bryan Haberberger <
notifications@github.com> wrote:

> Tested up, down, left, and right side resizing and both variations for
> each case (either increasing or decreasing the volume of the column) and
> all tests passed using Windows 8.1, Chrome logged in as han.yan@valpo.edu
> on projects 5330, 5497 and 5555 at t-pen.org/TPEN28/ . This is now up for
> testing at /TPEN28/
>
> When this development branch is approved, we need to push it to production
> before any other bug fix.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_417-23issuecomment-2D286800751&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=rbg8OsHds9bBBacNxPPnFd14XkhQMSilAql0rL4PNXg&s=BPOed7FLswRCjJUVbzA9RLfPf79xrL4eFcS982GILJA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPel-5FhnZnKIiDmW9Rybr68tUtsxWsks5rmBN1gaJpZM4MZ0Bp&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=rbg8OsHds9bBBacNxPPnFd14XkhQMSilAql0rL4PNXg&s=B6eRV-xBxQY_7TyF-ntwqOCGdLg7r93ZlKLSxBSyP04&e=>
> .
>



-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248
