### ISSUE TITLE
No add button in button management for Molly 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#419]
Projects affected 
private uploads
Project 1=5572
Project 2=5579
Project 3=5583
Project 4=5584

**Comment by thehabes** [comment]
The button is #addH, and there is not css, javscript or JSP code that conditionally hides or shows it.  If a user does not see this button, there has been a break on the page.  Below is a screenshot from each of the projectID's listed in order.  This is an official Could Not Replicate (On windows 7 on Chrome logged in as han.yan@valpo.edu)

![1](https://cloud.githubusercontent.com/assets/3287006/23862052/fa1d1acc-07d9-11e7-948e-141296a3e93c.png)
![2](https://cloud.githubusercontent.com/assets/3287006/23862056/fd0bb5e0-07d9-11e7-8469-9cd45d999664.png)
![3](https://cloud.githubusercontent.com/assets/3287006/23862060/000883c2-07da-11e7-991e-24a3e4b6ebdd.png)
![4](https://cloud.githubusercontent.com/assets/3287006/23862063/0261db82-07da-11e7-8b50-658abab26fb7.png)

**Comment by thehabes** [comment]
We will be doing a screen share this week to figure this out.

**Comment by thehabes** [comment]
This was breaking for all projects.  If you see the 'Add Tag' button on any button management's xml tab, that is a confirmation of the fix.  The ultimate confirmation is if Molly says she can see it after we put it up at  /TPEN/ and have her log in and check.
