### ISSUE TITLE
Delete line is now broken

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#425]

**Comment by Domhnall101** [comment]
this now works but merge is broken

**Comment by thehabes** [comment]
Tested deleting lines throughout the column and all tests passed using Windows 8.1, Chrome logged in as han.yan@valpo.edu on projects 5330, 5497 and 5555 at t-pen.org/TPEN28/. This is now up for testing at /TPEN28/

**Comment by thehabes** [comment]
same problems as with #424
