### ISSUE TITLE
Demotion

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#426]
A group leader should be able to demote other group leaders.  Or maybe just the project creator should have this ability.  Either way, if a user is promoted, this cannot be undone.  Users who have groups that constantly shift (like classes) need to be able to remove these promoted users from the group once they move on.  

We have a demote API we designed for the Newberry TPEN, this should be a fairly quick task.  Users (like Molly) have already noticed this and called out the issue.

**Comment by thehabes** [comment]
Up for testing on /TPEN28/.  We should consider moving this into /TPEN/ this week.

**Comment by Domhnall101** [comment]
project creator has clickable flag next to name. doesn't function but goes through the motions. Dont make the flag clickable
