### ISSUE TITLE
Merge should not have the ruler trace on it.

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#428]
A merge cursor would be nice, but `pointer` would be enough.

**Comment by thehabes** [comment]
Need to look at applyRuler() for this.  We need to be careful, as this function governs .deletable and .mergable which is necessary for most of the parsing functionality.  If we want to change how this works, we will have to check the change against the merge and delete functions that depend on .deletable and .mergable.

**Comment by cubap** [comment]
We don't need to apply the ruler in this case, but if it is dangerous, we
can just make it transparent when deleting or merging.

Patrick Cuba
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314-977-4249

On Wed, Mar 15, 2017 at 4:43 PM, Bryan Haberberger <notifications@github.com

**Comment by thehabes** [comment]
Yes, we want there not to be applyRuler() on lines that are meant to be merged or removed, but removing applyRuler() will remove them getting the class .mergable or .deletable, which will make it so the lines cannot be merged or deleted at all and some other cascading affects within the UI.  This isn't a simple turn off scenario, it requires recoding and looking at the whole of parsing to make sure we handle .deletable and .mergable correctly.  

Luckily, I have been able to separate out the delete line, merge line and add line scenarios within applyRuler(), so @cubap is right in saying that we can alter the reaction of #ruler1 based on those scenarios (like make it transparent if delete or merge scenario).  .deletable and .mergable are fighting with .parsing for what the cursor should be, so we will also have to resolve these class conflicts to make it perfect.

**Comment by thehabes** [comment]
```javascript
function applyRuler(line, deleteOnly){
            $("#imageTip").html("Add a Line");
            if(!tpen.screen.isAddingLines){
                if(deleteOnly){ //delete line
                    $("#imageTip").html("Delete Line");
                    if (line.attr("lineleft") !== line.next("div").attr("lineleft")) {
                        line.addClass('deletable');
                    }
                    line.css('cursor','pointer');
                }
                else{ //merge line
                    if (line.attr("lineleft") == line.next("div").attr("lineleft")) {
                        line.next("div").addClass('deletable');
                    }
                    line.addClass('deletable');
                    if($(".deletable").size()>1){
                        $(".deletable").addClass("mergeable");
                        $("#imageTip").html("Merge Line");
                    } 
                    else  {
                        $("#imageTip").html("Delete Line");
                    }
                    line.css('cursor','crosshair');
                }
            }
            else{ //add lines
                line.css('cursor','crosshair');
            }
            line.bind('mousemove', function(e){
                var imgTopOffset = $("#imgTop").offset().left; //helps because we can center the interface with this and it will still work.
                var myLeft = line.position().left + imgTopOffset;
                var myWidth = line.width();
                $('#imageTip').show().css({
                    left:e.pageX,
                    top:e.pageY+20
                });
                $('#ruler1').show().css({
                    left: myLeft,
                    top: e.pageY, 
                    height:'1px',
                    width:myWidth 
                });

            });
    }
```

**Comment by thehabes** [comment]
There are a couple of obvious ways we can change how this works, like binding the mousemove function on line only if it is one of the scenarios we want it, or moving $('#ruler1').show() out of the mousemove function and hide or show it based on the scenario.
