### ISSUE TITLE
magnifying tool not contained to container

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#444]

**Comment by thehabes** [comment]
The event is receiving the correct container to contain #zoomDiv in, but it refuses to work for the compare split div and full page split div.  It will be contained if you zoom inside the transcription area.  

This is a time pit and would be very difficult to chase.  We believe it has something to do with the split areas (.split) being position with float:right.  However, changing this has a very signigicant impact as it is how all the split areas are positioned, and changing how it works now could change how they position in the interface, both in a static state and in the resize math.  I think we need to leave this alone...
