### ISSUE TITLE
Development Team tab on About T-PEN page

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#445]
This information is incorrect and needs to be updated.  

![dt](https://cloud.githubusercontent.com/assets/3287006/24309771/2c493f66-109b-11e7-8949-33dbe520423f.png)

**Comment by thehabes** [comment]
Please review!

![dt](https://cloud.githubusercontent.com/assets/3287006/24413068/f3d312f8-139f-11e7-9a0d-2fcf520aa45b.png)

**Comment by thehabes** [comment]
Should Patrick be Senior Developer and Jon Deering be Web Developer now?

**Comment by thehabes** [comment]
Oh and I see SLU twice in the titles, Hold on

**Comment by thehabes** [comment]
Ok better

**Comment by finantj** [comment]
OK, let me edit this and come up with suitable changes.

tjf

On Tue, Mar 28, 2017 at 10:23 AM, Bryan Haberberger <
notifications@github.com> wrote:

> Ok better
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289806101&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=dmXlylRqZ-eE-MWUUBvbkR9xCMSv3WITBq5vDm49Jvg&s=JoviA5bxqy8U9uhhrQpJM7FzYG8t9RrrPivL4MZ12Mk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGrYbbuNdGud0790dnIjWNYy1rlM9mzDks5rqSX2gaJpZM4MoqFM&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=dmXlylRqZ-eE-MWUUBvbkR9xCMSv3WITBq5vDm49Jvg&s=yJbvFL8kv5ZNRCZNJ4dZ9OSNk2ndkpoK3AQG6q0KXCA&e=>
> .
>



-- 
-----------------------------
Thomas Finan, Ph.D., F.S.A.
Director, Walter J. Ong, S.J., Center for Digital Humanities
Associate Professor, Department of History
Saint Louis University
3800 Lindell Blvd.
Saint Louis University
St. Louis, MO  63108
finantj@slu.edu
office:  314-977-7180
cell:  314-401-6831

NOTE: This e-mail message may contain information that may be privileged,
confidential, and exempt from disclosure. It is intended for use only by
the person(s) to whom it is addressed. If you have received this message in
error, please do not forward or use this information in any way; delete it
immediately, and contact the sender as soon as possible by the reply option
or by telephone at 314-977-3573.  Thank you.

**Comment by thehabes** [comment]
Donal will be posting an idea for the list here as well, since the people on TPEN 1.0 are not the same as TPEN 2.X.  We need the separation.  Make sure names and Titles are right and have whatever credentials included you want.

**Comment by finantj** [comment]
OK.

We need to tease out whether not including certain people in later
development stages is going to step on toes (I doubt it, especially since
2.x is essentially home grown). I would still want to have appropriate
citation where necessary.

Other points of clarification will include the status of Tomas (who could
be included as a “visiting scholar,” but the fact is he isn’t really doing
anything on this at the moment).

tjf

On Tue, Mar 28, 2017 at 10:28 AM, Bryan Haberberger <
notifications@github.com> wrote:

> Donal will be posting an idea for the list here as well, since the people
> on TPEN 1.0 are not the same as TPEN 2.X. We need the separation. Make sure
> names and Titles are right and have whatever credentials included you want.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289807787&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=vAOPiYo_8Cg-zbfEG6s9syjnMM7_NZSMaPdQCpyWZjw&s=p_ApMqzLGXfHkeZUwEmvWrPXfDZwl-pQ1zqBx54IBEI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGrYbWe7ivhoMcKEy0i6SFqFSzx0oIHnks5rqSc3gaJpZM4MoqFM&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=vAOPiYo_8Cg-zbfEG6s9syjnMM7_NZSMaPdQCpyWZjw&s=JOVEtbesmjOsRqMxM0YL60qaQhEgxdUHWaTqf5iEoik&e=>
> .
>



-- 
-----------------------------
Thomas Finan, Ph.D., F.S.A.
Director, Walter J. Ong, S.J., Center for Digital Humanities
Associate Professor, Department of History
Saint Louis University
3800 Lindell Blvd.
Saint Louis University
St. Louis, MO  63108
finantj@slu.edu
office:  314-977-7180
cell:  314-401-6831

NOTE: This e-mail message may contain information that may be privileged,
confidential, and exempt from disclosure. It is intended for use only by
the person(s) to whom it is addressed. If you have received this message in
error, please do not forward or use this information in any way; delete it
immediately, and contact the sender as soon as possible by the reply option
or by telephone at 314-977-3573.  Thank you.

**Comment by thehabes** [comment]
This is the dev version of the about page.  I am not going to promise it will always be up, but this is the page you are working with.

http://165.134.241.141/TPEN28/about.jsp

**Comment by finantj** [comment]
ok cool.

On Tue, Mar 28, 2017 at 10:37 AM, Bryan Haberberger <
notifications@github.com> wrote:

> This is the dev version of the about page. I am not going to promise it
> will always be up, but this is the page you are working with.
>
> http://165.134.241.141/TPEN28/about.jsp
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__165.134.241.141_TPEN28_about.jsp&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=oJXkCAryreYt8hMk6QtIaoPPwYw-g3mOlwocar06Nyc&e=>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289810572&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=IE-O5_u8shJ8T6fE5d4jATvOs0ho0UDp6vBbjQGhPL0&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGrYbWeS-5FaYABb3fNeFne-5FuURW-2DnXqo0ks5rqSktgaJpZM4MoqFM&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=9OesAuBiSRP2K4prm6eG9AvirkGUid-JBJTpYb65tZ8&e=>
> .
>



-- 
-----------------------------
Thomas Finan, Ph.D., F.S.A.
Director, Walter J. Ong, S.J., Center for Digital Humanities
Associate Professor, Department of History
Saint Louis University
3800 Lindell Blvd.
Saint Louis University
St. Louis, MO  63108
finantj@slu.edu
office:  314-977-7180
cell:  314-401-6831

NOTE: This e-mail message may contain information that may be privileged,
confidential, and exempt from disclosure. It is intended for use only by
the person(s) to whom it is addressed. If you have received this message in
error, please do not forward or use this information in any way; delete it
immediately, and contact the sender as soon as possible by the reply option
or by telephone at 314-977-3573.  Thank you.

**Comment by finantj** [comment]
we should prominently display symbols for Mellon and NEH on the landing
page for T-Pen.  it doesn’t belong on this About page, but certainly on the
main login page.’

tj

On Tue, Mar 28, 2017 at 10:40 AM, Thomas Finan <finantj@slu.edu> wrote:

> ok cool.
>
> On Tue, Mar 28, 2017 at 10:37 AM, Bryan Haberberger <
> notifications@github.com> wrote:
>
>> This is the dev version of the about page. I am not going to promise it
>> will always be up, but this is the page you are working with.
>>
>> http://165.134.241.141/TPEN28/about.jsp
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__165.134.241.141_TPEN28_about.jsp&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=oJXkCAryreYt8hMk6QtIaoPPwYw-g3mOlwocar06Nyc&e=>
>>
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289810572&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=IE-O5_u8shJ8T6fE5d4jATvOs0ho0UDp6vBbjQGhPL0&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGrYbWeS-5FaYABb3fNeFne-5FuURW-2DnXqo0ks5rqSktgaJpZM4MoqFM&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=udf4vK8W4TRy2F55MI9zN-ch17xSPCuciDZGyXZwzGI&s=9OesAuBiSRP2K4prm6eG9AvirkGUid-JBJTpYb65tZ8&e=>
>> .
>>
>
>
>
> --
> -----------------------------
> Thomas Finan, Ph.D., F.S.A.
> Director, Walter J. Ong, S.J., Center for Digital Humanities
> Associate Professor, Department of History
> Saint Louis University
> 3800 Lindell Blvd.
> Saint Louis University
> St. Louis, MO  63108
> finantj@slu.edu
> office:  314-977-7180 <(314)%20977-7180>
> cell:  314-401-6831 <(314)%20401-6831>
>
> NOTE: This e-mail message may contain information that may be privileged,
> confidential, and exempt from disclosure. It is intended for use only by
> the person(s) to whom it is addressed. If you have received this message in
> error, please do not forward or use this information in any way; delete it
> immediately, and contact the sender as soon as possible by the reply option
> or by telephone at 314-977-3573 <(314)%20977-3573>.  Thank you.
>



-- 
-----------------------------
Thomas Finan, Ph.D., F.S.A.
Director, Walter J. Ong, S.J., Center for Digital Humanities
Associate Professor, Department of History
Saint Louis University
3800 Lindell Blvd.
Saint Louis University
St. Louis, MO  63108
finantj@slu.edu
office:  314-977-7180
cell:  314-401-6831

NOTE: This e-mail message may contain information that may be privileged,
confidential, and exempt from disclosure. It is intended for use only by
the person(s) to whom it is addressed. If you have received this message in
error, please do not forward or use this information in any way; delete it
immediately, and contact the sender as soon as possible by the reply option
or by telephone at 314-977-3573.  Thank you.

**Comment by Domhnall101** [comment]
here is hte revised list

do not post untill we have had a converation with Patrick


Development Team
T-Pen 2.0-2.8
Dr. Jim Ginther, Principal Investigator (2013-15)
Director, Center for Digital Theology, Saint Louis University
Dr. Thomas Finan, Principal Investigator (2016-present)
Director, Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Donal Hegarty, Project Manager
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Patrick Cuba, Lead Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Bryan Haberberger, Web Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Han Yan, Web Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University


T-Pen 1.0-1.9
Dr. Jim Ginther, Principal Investigator
Director, Center for Digital Theology, Saint Louis University
Dr. Abigail Firey, co-Principal Investigator
CCL Project Director, University of Kentucky
Dr. Tomás O’Sullivan, Research Fellow (2010-11)
Center for Digital Theology, Saint Louis University
Dr. Alison Walker, Research Fellow (2011-12)
Center for Digital Theology, Saint Louis University
Michael Elliot, Research Assistant
University of Toronto
Meredith Gaffield, Research Assistant
University of Kentucky
Jon Deering, Senior Developer
Center for Digital Theology, Saint Louis University
Patrick Cuba, Web Developer
Center for Digital Theology, Saint Louis University

**Comment by cubap** [comment]
Alison and Tomas were named on the grant, so they are RF with dates. Dates
could also be added to the other folks.

The heading "Development Team" is common on projects and refers to those
who developed the project, not the current maintenance team. I think it may
be more helpful to add another section recognizing the ongoing maintenance,
if this is desired.

The version released under Mellon was 2.0, so that is how the numbering
runs. 1.0 was technically ENAP (well, TPEN 1.0 was ENAP 2.0 and so...)
Donal, Bryan, and Han were on the maintenance team for 2.0 and though 2.8
is a big deal to us, it would be peculiar to call it out as a separate
team, especially since 28 is sort of a code word for us and we don't
display the version on the main page anymore. Maintenance has included real
new features and development, but that's how point releases work.

(looking at new messages)

Sam is/was our server admin for everything, not just this, so it isn't
something we would include unless Tom wants to build some relationship with
the library. If we include him, we should also list Han, definitely Eric,
and perhaps Daniel Shown.

Eric and Han have code in the back end, so maintenance or ongoing support
with dates should be credited to them as well. Seeing the replies, I think
a discrete section for Development and Support/Maintenance/whatevs is best.
I would be under both with different titles, similar to the 1.0/2.0
headings Donal has.

I agree that the logos ought to be on the page more obviously. Make the
funders happy, especially when we go back for more. The intro statement (as
we approach the 5 year mark) might be amended to say "*was *funded"
instead, since the ongoing maintenance has been on our dime and we are
seeking more. Also the link under T-PEN.org is to the dev server and weird.

Patrick Cuba
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314-977-4249

**Comment by Domhnall101** [comment]
thanks for that pat I will make changes accordingly


donal

On Tue, Mar 28, 2017 at 11:03 AM, Patrick Cuba <notifications@github.com>
wrote:

> Alison and Tomas were named on the grant, so they are RF with dates. Dates
> could also be added to the other folks.
>
> The heading "Development Team" is common on projects and refers to those
> who developed the project, not the current maintenance team. I think it may
> be more helpful to add another section recognizing the ongoing maintenance,
> if this is desired.
>
> The version released under Mellon was 2.0, so that is how the numbering
> runs. 1.0 was technically ENAP (well, TPEN 1.0 was ENAP 2.0 and so...)
> Donal, Bryan, and Han were on the maintenance team for 2.0 and though 2.8
> is a big deal to us, it would be peculiar to call it out as a separate
> team, especially since 28 is sort of a code word for us and we don't
> display the version on the main page anymore. Maintenance has included real
> new features and development, but that's how point releases work.
>
> (looking at new messages)
>
> Sam is/was our server admin for everything, not just this, so it isn't
> something we would include unless Tom wants to build some relationship with
> the library. If we include him, we should also list Han, definitely Eric,
> and perhaps Daniel Shown.
>
> Eric and Han have code in the back end, so maintenance or ongoing support
> with dates should be credited to them as well. Seeing the replies, I think
> a discrete section for Development and Support/Maintenance/whatevs is best.
> I would be under both with different titles, similar to the 1.0/2.0
> headings Donal has.
>
> I agree that the logos ought to be on the page more obviously. Make the
> funders happy, especially when we go back for more. The intro statement (as
> we approach the 5 year mark) might be amended to say "*was *funded"
> instead, since the ongoing maintenance has been on our dime and we are
> seeking more. Also the link under T-PEN.org is to the dev server and weird.
>
> Patrick Cuba
> Walter J. Ong S.J. Center for Digital Humanities
> Saint Louis University
> 314-977-4249 <(314)%20977-4249>
>
> On Tue, Mar 28, 2017 at 10:31 AM, finantj <notifications@github.com>
> wrote:
>
> > OK.
> >
> > We need to tease out whether not including certain people in later
> > development stages is going to step on toes (I doubt it, especially since
> > 2.x is essentially home grown). I would still want to have appropriate
> > citation where necessary.
> >
> > Other points of clarification will include the status of Tomas (who could
> > be included as a “visiting scholar,” but the fact is he isn’t really
> doing
> > anything on this at the moment).
> >
> > tjf
> >
> > On Tue, Mar 28, 2017 at 10:28 AM, Bryan Haberberger <
> > notifications@github.com> wrote:
> >
> > > Donal will be posting an idea for the list here as well, since the
> people
> > > on TPEN 1.0 are not the same as TPEN 2.X. We need the separation. Make
> > sure
> > > names and Titles are right and have whatever credentials included you
> > want.
> > >
> > > —
> > > You are receiving this because you were assigned.
> > > Reply to this email directly, view it on GitHub
> > > <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_
> > CenterForDigitalHumanities_TPEN28_issues_445-
> 23issuecomment-2D289807787&d=
> > DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=vAOPiYo_8Cg-
> > zbfEG6s9syjnMM7_NZSMaPdQCpyWZjw&s=p_ApMqzLGXfHkeZUwEmvWrPXfDZwl-
> > pQ1zqBx54IBEI&e=>,
> > > or mute the thread
> > > <https://urldefense.proofpoint.com/v2/url?u=https-
> > 3A__github.com_notifications_unsubscribe-2Dauth_
> > AGrYbWe7ivhoMcKEy0i6SFqFSzx0oIHnks5rqSc3gaJpZM4MoqFM&d=
> DwMFaQ&c=Pk_HpaIpE_
> > jAoEC9PLIWoQ&r=lOgeT00Md_gx0E8LjCrwBQ&m=vAOPiYo_8Cg-zbfEG6s9syjnMM7_
> > NZSMaPdQCpyWZjw&s=JOVEtbesmjOsRqMxM0YL60qaQhEgxdUHWaTqf5iEoik&e=>
> > > .
> > >
> >
> >
> >
> > --
> > -----------------------------
> > Thomas Finan, Ph.D., F.S.A.
> > Director, Walter J. Ong, S.J., Center for Digital Humanities
> > Associate Professor, Department of History
> > Saint Louis University
> > 3800 Lindell Blvd.
> > Saint Louis University
> > St. Louis, MO 63108
> > finantj@slu.edu
> > office: 314-977-7180 <(314)%20977-7180> <(314)%20977-7180>
> > cell: 314-401-6831 <(314)%20401-6831> <(314)%20401-6831>
> >
> > NOTE: This e-mail message may contain information that may be privileged,
> > confidential, and exempt from disclosure. It is intended for use only by
> > the person(s) to whom it is addressed. If you have received this message
> in
> > error, please do not forward or use this information in any way; delete
> it
> > immediately, and contact the sender as soon as possible by the reply
> option
> > or by telephone at 314-977-3573 <(314)%20977-3573> <(314)%20977-3573>.
> Thank you.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_
> CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289808829&d=
> DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=Ob88fw3QcoIhBawyjgurXw&m=
> BdVmjOBtMdz4fyTPQUUc_L6a0BvcI1vBQnKZqdvbI3M&s=
> RhYty0oHGqtDIqvPWWdxFUAZbJX32eoIG5n_VXGSrho&e=>,
> > or mute the thread
> > <https://urldefense.proofpoint.com/v2/url?u=https-
> 3A__github.com_notifications_unsubscribe-2Dauth_
> ABETvbJrCsmF2j8ZqnoHul8iUAyWPseiks5rqSfvgaJpZM4MoqFM&d=DwMFaQ&c=Pk_HpaIpE_
> jAoEC9PLIWoQ&r=Ob88fw3QcoIhBawyjgurXw&m=BdVmjOBtMdz4fyTPQUUc_
> L6a0BvcI1vBQnKZqdvbI3M&s=6XBn5UHmpT5eNSINLJ85fqcvZn0ARVJ8GV7y6k6psVw&e=>
> > .
> >
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_445-23issuecomment-2D289818879&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=YgxO1w3C_Olbz3aG0Faci6jx2GZKuULFiWPktAsJyaY&s=CHsAqRARSRpJOk68Ilefh5c0DkeSRARiOVS4TX7W-RU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPRe1HT-5FA55LzoDVLPqUqPo4wCKU8ks5rqS88gaJpZM4MoqFM&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=YgxO1w3C_Olbz3aG0Faci6jx2GZKuULFiWPktAsJyaY&s=fisZwPrlCxboG3RwAepnGrTUYA8AonssRUL_lqatD94&e=>
> .
>



-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248

**Comment by Domhnall101** [comment]
Support/Maintenance Team
T-Pen 2.0-2.8
Dr. Jim Ginther, Principal Investigator (2013-15)
Director, Center for Digital Theology, Saint Louis University
Dr. Thomas Finan, Principal Investigator (2016-present)
Director, Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Donal Hegarty, Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Patrick Cuba, Lead Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Bryan Haberberger, Web Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University
Han Yan, Web Developer
Walter J. Ong S.J. Center for Digital Humanities, Saint Louis University

T-Pen 2.0
Dr. Jim Ginther, Principal Investigator
Director, Center for Digital Theology, Saint Louis University
Dr. Abigail Firey, co-Principal Investigator
CCL Project Director, University of Kentucky
Dr. Tomás O’Sullivan, Research Fellow (2010-11)
Center for Digital Theology, Saint Louis University
Dr. Alison Walker, Research Fellow (2011-12)
Center for Digital Theology, Saint Louis University
Michael Elliot, Research Assistant
University of Toronto
Meredith Gaffield, Research Assistant
University of Kentucky
Jon Deering, Senior Developer
Center for Digital Theology, Saint Louis University
Patrick Cuba, Web Developer
Center for Digital Theology, Saint Louis University

**Comment by cubap** [comment]
Minor notes:

- T-PEN is all caps.
- Jim was the Director of the Center for Digital *Humanities *from 2013-15
- Tom isn't the PI, as far as I know. He can be listed as Director, since
that guides support (and people like to know who to blame).
- Han Yan has no dates listed
- Eric Smith is not listed and he was far more entrenched in T-PEN than
anyone since Jon Deering.
- I would probably drop the 2.0-2.8 heading since when we launch 2.85 or
2.9 we'll just have to update it. I think "maintenance" implies the most
recent version, but "ongoing" or "active" could be added to indicate active
development.

Patrick Cuba
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314-977-4249

**Comment by thehabes** [comment]
Changes are made and implemented.  Up for review at http://165.134.107.94/TPEN/about.jsp

![33](https://user-images.githubusercontent.com/3287006/32069500-fc50426a-ba4e-11e7-8e50-1cb36abffb5f.png)
