### ISSUE TITLE
insert perseus as tool option for pull down

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#455]
http://www.perseus.tufts.edu/

**Comment by thehabes** [comment]
The tool with the label Latin Dictionary is URL http://www.perseus.tufts.edu/hopper/resolveform?lang=latin

**Comment by thehabes** [comment]
So Perseus is included in the tools, but perhaps it has the wrong label?

**Comment by thehabes** [comment]
I see what's going on.  The tools are not coded as enums like the other tools.  We hard code them to project.jsp in the DOM and fire the addTool() function based off that set of tools.   Old projects have other tools that were available at the time (like Latin Dictioniary) or other manually added in user tools.

For Perseus to be a part of the set everyone sees without having to add it in manually, we have to hard code Latin Dictionary into project.jsp and tell the .jsp to expect another index in its tool check logic.
