### ISSUE TITLE
check for text before warning about text loss when deleting column in parsing

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#456]
Pat suggested this check already exisited. can we pull that code to do this check. If text present give the warning if not - don't

**Comment by cubap** [comment]
see transcription.js line 583

Patrick Cuba
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314-977-4249

**Comment by thehabes** [comment]
```javascript
function removeColumn(column){
    if (column.attr("hastranscription") === "true"){
        var cfrm = confirm("This column contains transcription data that will be lost.\n\nContinue?");
        if (!cfrm) return false;
    }
    var colX = column.attr("lineleft");
    // collect lines from column
    var lines = $(".parsing[lineleft='" + colX + "']");
    lines.addClass("deletable");
    tpen.screen.nextColumnToRemove = column;
    removeColumnTranscriptlets(lines, false);


}
```

The actual remove function is doing the right thing.  The code that designates a column hastranscription or not is doing the wrong thing.   transcribe.js line 3181

**Comment by thehabes** [comment]
This designation is done in gatherColuns()
`tpen.screen.gatheredColumns.push([colX, colY, colW, colH, $(line).attr("lineserverid"), $lastLine.attr("lineserverid"), true]);`
and is looked for in linesToColumns()
```javascript
columns.push("<div class='parsingColumn' lineleft='", gatheredColumns[j][0], "'",
            " linetop='", gatheredColumns[j][1], "'",
            " linewidth='", gatheredColumns[j][2], "'",
            " lineheight='", gatheredColumns[j][3], "'",
            " hastranscription='", gatheredColumns[j][6] == true, "'",
            " startid='", startID, "'",
            " endid='", endID, "'",
            " style='top:", scaledY, "%;left:", scaledX, "%;width:", scaledW, "%;height:", scaledH, "%;'>",
            "</div>");
```

true is hard coded during designation, so during the UI build
`hastranscription='", gatheredColumns[j][6] == true`
is always true, thus the confirm will be thrown every time no matter what

**Comment by thehabes** [comment]
To fix this, during designation in gatherColumns(), we have to do a text check over each line that could be in the column to hand over a proper true/false flag.

**Comment by cubap** [comment]
Is this easier than just checking each line before it is deleted?

`$(".transcriptlet[data-lineid='"+$(e).attr("data-lineid")+"']").find(".theText").val().length > 0`

`data-lineid` is something else now, but it works the same way. This might be cheaper than the `hastranscription` attribute because it is only run on delete, instead of iterating every time columns are generated.
