### ISSUE TITLE
Dereferencable canvas URLs

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#47]
The canvas @id provided by the manifest servlet is not a dereferenceable URL.  This is because we sort of fake it because the canvas is in the SQL, but we could make a small shim that builds the JSON canvas representation and returns it.

**Comment by cubap** [comment]
Yes ++ to this.

**Comment by thehabes** [comment]
I have successfully created this servlet with commit 2ec5840.  However, in web.xml I try to redirect the url to the canvasSerlvet like so

<servlet-mapping>
        <servlet-name>CanvasServlet</servlet-name>
        <url-pattern>/canvas/*</url-pattern>
  </servlet-mapping>

however, our canvases are named like http://165.134.241.141/TPEN28/MS21470/canvas/13186850.  The redirect will not work because of /MS21470/canvas, so to get a canvas the URL needs to be http://165.134.241.141/TPEN28/canvas/13186850, which means we would have to name our canvases differently for this to work when it comes from the servlet and people use its @id.  For more info on why it MUST work this way, see 
http://stackoverflow.com/questions/26732/java-lang-illegalargumentexception-invalid-url-pattern-in-servlet-mapping/26744#26744

**Comment by thehabes** [comment]
This is much more robust and probably an alternative, I like implementing this over the limited servlet mapping approach from old T-PEN.  I am putting this on the back log for now, I want to get to bug tickets first.

https://github.com/paultuckey/urlrewritefilter

**Comment by thehabes** [comment]
How about we just take out the /MSXXXX/ for now.  Its not IIIFy, but its better than what others are doing.
