### ISSUE TITLE
Endpoints and `@id` inclusion in project JSON

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#471]
`project/:projectID` and `manifest/:projectId` return annotationLists and annotations without `@id` properties. At the moment, there are also not servlets to dereference those items.

### AnnotationList
*@id* : `(TPEN)/project/:projectID/annotations/:folioID`

### Annotation
*@id* : `(TPEN)/annotation/:lineID`

**Comment by cubap** [comment]
lists in `buildPage()`

lines in `annos.getAllAnnotations()`

**Comment by thehabes** [comment]
Will be completing and testing with @cubap today

**Comment by thehabes** [comment]
Test by viewing
http://165.134.241.141/TPEN28/manifest/4080

**Comment by thehabes** [comment]
"otherContent" : [ {
        "@id" : "http://165.134.241.141/TPEN28/project/4080/annotations/105420",
        "@type" : "sc:AnnotationList",
.
.
.
{
          "@id" : "http://165.134.241.141/TPEN28/line/101083800",
          "_tpen_line_id" : "line/101083800",
          "@type" : "oa:Annotation",

.
.
.
