### ISSUE TITLE
Tooltips in view full page

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#475]
Now that we are bringing the lines over, when you hover over a line it tries to display the transcirption on the line.  However, this div[role="tooltip"]  has no defined CSS and it's z-index is too low.  If you are lucky, you will see a word or two in the buffer between the interfaces.  

A couple options
1. Don't do the tooltips
2. Make the z-index proper, and probably skin differently.  

Here is what it looks like when I give it a proper z-index

![dd](https://cloud.githubusercontent.com/assets/3287006/25751914/3a7028dc-317c-11e7-87a7-640f121418cc.png)

**Comment by thehabes** [comment]
updated css on t-pen.org so that it has a proper z-index, so you can see them there now.  I didn't even know we did this.  Do we want to keep it?  Do we want to skin it at all?

**Comment by cubap** [comment]
The CSS in 2.0 leaves them at the bottom or top of the tool, but this looks fine to me.
