### ISSUE TITLE
Self closing XML tags

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#482]
buttons.jsp
- Allow for self closing tag creation here.  Fix the error message that pops up for invalid tags, make one that allows just the " /" and lets the user know they are making self closing tags.

project.jsp
- Make sure self closing tags display correctly in the list of all existing tags

transcription.html
- Make sure self closing tags display correctly in the list of all existing tags.
- Make sure self closing tags are inserted into the text stream correctly.
- These tags are only meant for insertion, so handle when a user selects a text range and clicks a self closing tag (in a 0 - N index scenario, insert at the lowest interval)

**Comment by thehabes** [comment]
Ready for testing at http://165.134.105.25/TPEN28/

**Comment by thehabes** [comment]
Ready for testing at http://165.134.105.25/TPEN28/

**Comment by Domhnall101** [comment]
tags seem to work with the / in both versions of t-pen however the view of
the buttons in the tray in 2.8 are not rendering correctly
see image below



On Fri, Jun 16, 2017 at 10:48 AM, Bryan Haberberger <
notifications@github.com> wrote:

> Ready for testing at http://165.134.105.25/TPEN28/
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__165.134.105.25_TPEN28_&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=8uabU11m4MGQ6PZlhqpsSkWwCbc8Fynk9dVInSdHaVQ&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_482-23issuecomment-2D309062134&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=X2XxUQknQNWzQ7WL2GpFH1EV1jbFWnOWxP2dyegDzvA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPYuFfbNvsIBXCTTGLtZrWzLkfVzvks5sEqPOgaJpZM4N3YQS&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=VCOIAy6FUns4jNi6g6HNsLAbs9qw6--XtztV9LdyjDc&e=>
> .
>



-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248

**Comment by Domhnall101** [comment]
they should lok like this



On Fri, Jun 16, 2017 at 12:51 PM, Domhnall Ó h'Éigheartaigh <
dhegarty@slu.edu> wrote:

> tags seem to work with the / in both versions of t-pen however the view of
> the buttons in the tray in 2.8 are not rendering correctly
> see image below
>
>
>
> On Fri, Jun 16, 2017 at 10:48 AM, Bryan Haberberger <
> notifications@github.com> wrote:
>
>> Ready for testing at http://165.134.105.25/TPEN28/
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__165.134.105.25_TPEN28_&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=8uabU11m4MGQ6PZlhqpsSkWwCbc8Fynk9dVInSdHaVQ&e=>
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_482-23issuecomment-2D309062134&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=X2XxUQknQNWzQ7WL2GpFH1EV1jbFWnOWxP2dyegDzvA&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPYuFfbNvsIBXCTTGLtZrWzLkfVzvks5sEqPOgaJpZM4N3YQS&d=DwMCaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=sm1um-zQfoSXDBy5grbO0vZXH0wRomOacm1TnrEBR7w&s=VCOIAy6FUns4jNi6g6HNsLAbs9qw6--XtztV9LdyjDc&e=>
>> .
>>
>
>
>
> --
> Donal Hegarty
> Project Manager/UX Designer
> Walter J. Ong S.J. Center for Digital Humanities
> Saint Louis University
> 314 9774248 <(314)%20977-4248>
>
>
>


-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248

**Comment by thehabes** [comment]
I can't see your images, but I know what you were getting at.  Try now.  They look like this.

![tt](https://user-images.githubusercontent.com/3287006/27238537-e80ee442-5292-11e7-9f43-cda487049fa8.png)

**Comment by cubap** [comment]
Self-closing tags also shouldn't be sent to the tag tracker. This works in 2.0 interface, so maybe you've sidestepped something.
