### ISSUE TITLE
T-PEN 2.8 needs default setting to load with new project

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#485]
The following should be active in a default set up

Cappelli Abbreviations
Compare Pages
Parsing Adjustment
Preview Tool
History Tool
Linebreaking Tool
View Full Page
XML Tags
Special CharactersI
Inspect 
Page Tools
enigma
latin vulgate

**Comment by thehabes** [comment]
Cappelli Abbreviations
Compare Pages
Parsing Adjustment
Preview Tool
History Tool
Linebreaking Tool
View Full Page
XML Tags
Special CharactersI
Inspect
Page Tools

Are tools that are only connected with a user, not a project.  A user that has these tools has them active for all projects and potential future projects.  When a user is accepted into T-PEN I can set those to default to on, but if that user changes whether a tool is active or not it will apply to all of their projects, they can not be controlled on a per project basis.  When a project is created, it has no effect on these tools. Whatever the user has set as an active tool will appear in that new project.

```java
//Called from admin suite's approveUser() method
public static void initializeTools(int uid) throws SQLException {       
      Tool t;
      for (Tool.tools iter : tools.values()) {
          switch(iter){
                case preview:
                  t = new Tool(iter, uid);
                break;
                case compare:
                  t = new Tool(iter, uid);
                break;
                case parsing:
                  t = new Tool(iter, uid);
                break;
                case abbreviation:
                  t = new Tool(iter, uid);
                break;
                case history:
                  t = new Tool(iter, uid);
                break;
                case linebreak:
                  t = new Tool(iter, uid);
                break;
                case fullpage:
                  t = new Tool(iter, uid);
                break;
                case xml:
                  t = new Tool(iter, uid);
                break;
                case characters:
                  t = new Tool(iter, uid);
                break;
                case inspector:
                  t = new Tool(iter, uid);
                break;
                default:
                  //Not a default tool, do nothing.
                
          }
      }
   }
```

enigma
latin vulgate
latin dictionary
Are connected to the project.  When a project is created, we can set these to default to on or off by simply adding them in or choosing not to.
```java
//called from new Project() instantiation
/**
    * Add the standard latin tools to a project
    */
   private void initializeTools(Connection conn) throws SQLException {
      addUserTool(conn, "Latin Vulgate", "http://vulsearch.sourceforge.net/cgi-bin/vulsearch");
      addUserTool(conn, "Latin Dictionary", "http://www.perseus.tufts.edu/hopper/resolveform?lang=latin");
      addUserTool(conn, "Enigma", "http://ciham-digital.huma-num.fr/enigma/");
   }
```

**Comment by thehabes** [comment]
Worked it out with Patrick.  Up for testing at http://165.134.107.94/TPEN/
