### ISSUE TITLE
Peek-Zoom removes focus from transcriptlet

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#531]
The cursor disappears so you cannot peek and keep typing. This does not affect the classic interface.

**Comment by thehabes** [comment]
Yeah, but you can't type while holding ctrl+alt.  It does a ton of crazy things, even in the classic interface, because those are hotkeys for accessibility things and what not...

**Comment by cubap** [comment]
This wasn't clear. The focus is removed. That is the issue, not that the textarea is disabled.

1. Start typing "in nomine omni"
2. Stop because I can't quite read the next letter
3. Hold `CTRL`+`SHIFT` to peek in and see the "s"
4. Release `CTRL`+`SHIFT` and type "s"
5. Notice there is no "s" and look at the keyboard and carefully type again
6. Still no "s"
7. "s" "s" "s" "s" "s" "s" "s"... nothing
8. Oh, I see. Move the mouse and click in the textarea
9. Type "s"
10. Sigh and push back from the desk for a hot minute.

**Comment by thehabes** [comment]
OOooooo OK OK yes that is not what I checked.
