### ISSUE TITLE
What have you done?!

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#538]
We're going to blame @thehabes, because it feels good.
The TPEN Classic interface no longer triggers saves. Also #536 shows that the "enter" key event isn't firing, so it seems that something unintended has run over the attached handlers.

**Comment by cubap** [comment]
There is an email from a user reporting this behavior.

>Ani Sh****yan (sh****@yandex.ru) says:
Dear T-pen team,
I have some issue with T-pen.  My changes are not being saved in t-pen. I would like to ask you to help me. Thank you in advance.

**Comment by thehabes** [comment]
Hmm so definitely too far buried in the jsp for me to really be able to know just by looking at the page.  However, it seems to me that `isMember` and/or `isAdmin` detection is off.  

In transcription.js
```javascript
Interaction.moveTextToNextBox: function() {
    if(!isMember && !permitModify)return false;
   .
   .
   .
}
```
This clause is stopping it dead.

I can't seem to see where `isMember` is set in the console on transcription.jsp, and so cannot breakpoint around its factors.  I will need to inject some   
```javascript
out.println("console.log(" + isAdmin + ");");
out.println("console.log(" + isMember + ");");
```
into transcription.jsp and re-deploy to prd-01 to learn more.  

I cannot replicate this issue on dev-01.

**Comment by cubap** [comment]
This looks like the right path. I would suspect that the recent messing with `isAdmin` was controlled on transcription.html, which uses transcribe.js, and not on transcription.jsp, which only has transcription.js (I think)

**Comment by thehabes** [comment]
Oh I can replicate on dev.  Learning more, h/o

**Comment by thehabes** [comment]
Ah crap it is @thehabes fault.  https://github.com/CenterForDigitalHumanities/TPEN28/pull/534/files#diff-57873cfb715f2e20e4c2b755f5a55d5c54c8ae90be59844213d8be879f292518.  Those variables need to be out.println, that is how it sets the globals in transcription.js.  I thought they were my own comments, my bad.

**Comment by cubap** [comment]
I don’t just throw accusations around pell-mell. I’m glad it wasn’t too hard to find.

**Comment by thehabes** [comment]
Hotfix PR is in

**Comment by thehabes** [comment]
Hotfix deployed to production.  Tested with project 4080, the lines save now.
