### ISSUE TITLE
Add a new XML entry

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#554]
Make sure this respects position and still works against broken data sets. For a project with a broken data set, if the getter is returning all XML entries no matter what, adding a XML entry can base its position as one more than the max position.  Note that position MUST NOT be 0.

Ensure the mapping for this function is what it needs to be in web.xml

**Comment by thehabes** [comment]
Adding a new XML entry in the interface does save an entry. It's position is one greater than the gap floor. The text and description are not the one I typed in.

It does come back out, but shows an XML entry that had already existed, not what I typed.  Definitely a bit goofy and needs fixed.

Adding a new XML entry should always add it to the spot one greater than the max position value instead of one greater than the gap floor. We know the GETter will handle it and show it right. This will stop the phantom XML entry behavior. TODO.

**Comment by cubap** [comment]
This is extraordinary. What a can of worms.

**Comment by cubap** [comment]
ummm... Add a new tag always deletes the tag (if it exists) first. This is the failsafe of a madman.

```java
public TagButton(int projectID, int position, String tag, Boolean project, String description) throws SQLException {
      Connection j = null;
      PreparedStatement stmt = null;
      try {
         TagButton t = new TagButton(projectID, position, true);
         t.deleteTag();
      } catch (Exception e) {
            getLogger(TagButton.class.getName()).log(SEVERE, null, e);
      }
      try {
         String query = "insert into projectbuttons(project,position,text,description) values (?,?,?,?)";
         j = getConnection();
         stmt = j.prepareStatement(query);
...
