### ISSUE TITLE
Confirm no hotkey creation by UID

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#566]
remove if possible #564 is the comment in `addKey.java`

**Comment by thehabes** [comment]
I do not see any exposed UIs for users to do this.  Any "Hotkey" interactions are for entries connected to projects, not users.  Note that there are entries in the table where UID > 0.  Some legacy interfaces must have done this.

**Comment by thehabes** [comment]
Confirmed that it is not used.  Make a new issue to take it out.
