### ISSUE TITLE
CTRL+# hotkey labels should stop at "0"

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#567]
New 2.8 interface shows the shortcut label on all button but should stop at 10.

**Comment by thehabes** [comment]
`0` has been eliminated from the DB and logic.  `ctrl+0` is no longer a thing.

2.8 interface script needs to be updated to stop adding `ctrl+` label after the 10th button.

**Comment by thehabes** [comment]
Also see #572

**Comment by thehabes** [comment]
127 is a blank
