### ISSUE TITLE
Jump to Page glitch

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#579]
Every item in the dropdown has "unknown" before it.  The little book .gif is off a bit.

![image](https://user-images.githubusercontent.com/3287006/109864890-0556a580-7c29-11eb-97a7-e4318bc0b331.png)

**Comment by cubap** [comment]
Yeah, this is actually supposed to have the lastModifiedFolio() behind it, I believe.
