### ISSUE TITLE
Delete Project Permissions Glitch

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#584]
Login as han.yan@valpo.edu

Go to http://t-pen.org/TPEN/project.jsp?projectID=4080.  You cannot delete any projects in All Projects.
Go to http://t-pen.org/TPEN/project.jsp?projectID=5330.  You can delete any project in All Projects.

This doesn't seem right.

**Comment by thehabes** [comment]
Update - Once I deleted some other projects, all of the sudden I am no longer a member of 5330 and cannot load that page.

**Comment by cubap** [comment]
confirmed

```java
if (isAdmin) {
    out.print("<span class=\"delete ui-icon ui-icon-closethick right\" onclick=\"deleteProject(" + UID + "," + userProjects[i].getProjectID() + "," + "'" + StringEscapeUtils.escapeJavaScript(mList.getTitle()) + "'" + ");\">delete</span></li>");
} else {
    out.print("</li>");
}
```

**Comment by cubap** [comment]
Although, it looks like that this error was introduced, so I will probably just fix that, so we don't change the UI for users.

![image](https://user-images.githubusercontent.com/1119165/110019750-6f854e00-7cee-11eb-8cca-bc54c5465c38.png)
