### ISSUE TITLE
Peek-Zoom cannot recover from tall lines

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#587]
In the 2.8 interface, when peek-zooming on a tall line the workspace often disappears. Worse, when releasing Peek-Zoom, the workspace usually snaps to the top of the screen and stays there while tabbing through lines. <kbd>ESC</kbd> does not reset it, but entering splitscreen and exiting back to fullscreen does.

**Comment by thehabes** [comment]
Adding a fire to fullPage() to line it up (which is what entering splitscreen then exiting fires)

**Comment by thehabes** [comment]
Nope.  Figured out it was transitions causing this.  In other similar scenarios, applying and remove `.noTransition` works, and seems to work well here.  Much simpler.
