### ISSUE TITLE
capelli vs. cappelli

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#597]
Why this came up is because of http://t-pen.org/TPEN/transcription.jsp?projectID=6559.  You will notice the image does not load on http://t-pen.org/TPEN/transcription.html?projectID=6559.  

It is a capelli image, I think.  The error on transcription.html is a 404 from https://centerfordigitalhumanities.github.io/capelli/.

Do we need to make sure our T-PEN deploy uses imageResize for the transcription images, or do we need to look into the capelli?

**Comment by cubap** [comment]
"capelli" should be "cappelli" so there's at least that typo that can be fixed.

2.8 was intentionally taken off of `imageResize` to avoid triggering image parsing that was broken.

// just info.

**Comment by thehabes** [comment]
I have replaces all instances of `capelli` with `cappelli`.

```java
Searching 731 files for "capelli"

0 matches
``` 

This error still happens, which makes me believe it is spelled "capelli" in the data :(

**Comment by thehabes** [comment]
Also, it is spelled both ways throughout the code.  It is hard to refactor without knowing what will actually break something relying on this spelling pattern.  This means these projects are forced into transcription.jsp and cannot use transcription.html, which is bad.  We need to figure this out.

**Comment by thehabes** [comment]
Prolly gotta do a find an replace for the data.  @cubap will do this.

**Comment by thehabes** [comment]
Still will not load.  Server breaks on the following image
```java
08-Apr-2021 17:50:27.887 INFO [ajp-nio-8109-exec-10] textdisplay.Folio.loadLocalImage Archive for folio %d was %s
08-Apr-2021 17:50:27.887 INFO [ajp-nio-8109-exec-10] textdisplay.Folio.getImagePath Loading private image /images/userimages/Shahnazaryan/23197/Shahnazaryan2140/8375.0004.JPG.jpg
```
