### ISSUE TITLE
inconsistent checks for `otherContent[0].resources`

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#605]
```js
function loadTranscriptionCanvas(canvasObj, parsing, tool, restore) {
    var noLines = canvasObj.otherContent[0].resources.length === 0;
    var canvasAnnoList = "";
```
line:1437 of transcribe.js, on a new IIIF Manifest Import there is a canvasObj that has no transcription, so otherContent[0] is undefined.

Upstream from this line:917 where a list is added if it isn't there, but the check is only for `this.otherContent` rather than its Array-ness.

**Comment by cubap** [comment]
changed to `var noLines = !(canvasObj.otherContent[0]?.resources.length > 0);` on the server... testing it out.

**Comment by cubap** [comment]
Maybe this is something... 
```
21-Apr-2021 14:05:39.377 SEVERE [ajp-nio-8109-exec-5] edu.slu.tpen.transfer.JsonLDExporter.buildPage null
21-Apr-2021 14:05:39.390 INFO [ajp-nio-8109-exec-5] textdisplay.Folio.getUncachedImageStream Connection method for https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100056056646.0x000001/manifest.json was none
```
Is this what is happening? Where is the manifest.json coming from and is it trying to load it as an image?

**Comment by cubap** [comment]
That's the manuscript archive field.... I fixed it.

**Comment by cubap** [comment]
but the manifest that is built by TPEN is empty, which is less than ideal.
It is possible that the image is returning a 403? It downloads the image when I click a link to it, but I get a 403 when I try to go to it in a tab... so I'm not sure what that means.

**Comment by cubap** [comment]
```
"canvases" : [ { }, { }, { }, { }, { }, { }, { }, { }, { }, { }, { }, { }, { }, { } ]
```

**Comment by cubap** [comment]
Final verdict: This needs a better error and almost definitely is a 403 from the imageURI

**Comment by cubap** [comment]
`https://api.bl.uk/image/iiif/ark:/81055/vdc&100057706553.0x000037/full/max/0/default.jpg` needs to be "_" not "&"

This is silly and I don't know why it is there. It should have been 404, not 403.

**Comment by cubap** [comment]
It gets worse... The manifest has this right so somewhere in the `ClassicProjectFromManifest` workflow it is substituting an ampersand for underscores.

**Comment by thehabes** [comment]
CreateProjectServlet.java line 159ish
`int folioKey = createFolioRecordFromManifest(city, canvas.getString("label"), imageName.replace('_', '&'), archive, m.getID(), 0);`

ClassicProjectFromManifest.java line 119ish
`int folioKey = createFolioRecordFromManifest(city, canvas.getString("label"), imageName.replace('_', '&'), archive, mss.getID(), 0);`
