### ISSUE TITLE
transcription.html

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#607]
Externally loaded manifests save canvases to transcriptionCanvases instead of tpen.manifest so scrubFolios() hits an undefined error.

**Comment by thehabes** [comment]
It was even messier.  All good, it was just a situation that had not been thought about in a while.  `loadTranscription()` could use some serious optimizing and code cleanup.  All the "just read it and load" scenarios should work (some testing todo).  I should figure out a succinct way for it to ignore the login check by the end of the day.
