### ISSUE TITLE
Content Negotiation and Browser Cache

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#639]
I noticed browser cache can trick you here.  This may have made testing frustrating for you, as changing the header wasn't enough to tell the browser to get the resource again instead of using the one in cache.  This meant I was getting the wrong version at times.

The browser cache should respect the need for the new resource.  Our server will have to respond to browsers in a way that makes them have some respect.

**Comment by thehabes** [comment]
This one may be a bit out of scope for the capstone, but we found it because of them.  Consider this a stretch goal, as you would have to mess around in the client script and the back end code at the same time to accomplish this.

**Comment by tvay11** [comment]
680-browsercache
