### ISSUE TITLE
Review transcription.html for redundancy

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#65]
In clearing the old code, it seems there is a bit, especially around parsing that may be repeated in transcription.html and newberry.js (now transcribe.js after PR). I can look at it, but it may be quicker for you to just read through and see if anything seems off. The final move here is probably to move anything that can be taken off the page itself to transcribe.js.

**Comment by cubap** [comment]
PR #66

**Comment by thehabes** [comment]
Checking all functions on transcription.html for any that match in transcribe.js
Then I will see if any that aren't exact matches have functions by a similar name
Then I will check page load and event attachments
