### ISSUE TITLE
Workspace goes off screen

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#67]
For projects with the right kind of lines, the workspace will be off screen.  Since the screen is no longer scrollable, the user never sees the workspace.

**Comment by thehabes** [comment]
http://165.134.241.141/TPEN28/transcription.html?projectID=4417

http://165.134.241.141/TPEN28/transcription.html?projectID=5335

**Comment by cubap** [comment]
There is a huge gap above the line (in 4417). It looks like the first line
of a column defaults to showing everything above it. There should probably
be a max for that. I can't make the workspace run off in 5335.

Patrick Cuba
Center for Digital Humanities
Saint Louis University
314-977-4249

On Wed, Oct 26, 2016 at 4:42 PM, Bryan Haberberger <notifications@github.com

**Comment by cubap** [comment]
I can also change the amount it correct by to ensure the whole workspace
will be on-screen.

Patrick Cuba
Center for Digital Humanities
Saint Louis University
314-977-4249

**Comment by thehabes** [comment]
It isn't all the way off screen in 5335, but it is about chopped in half to the point where I can't see my buttons.  Unless a user knows to move the workspace, this can seem like a break-on-load.  See image.

![image](https://cloud.githubusercontent.com/assets/3287006/19746655/f4433c0c-9b9c-11e6-83f8-ae9b4ed382df.png)

**Comment by thehabes** [comment]
Heading out for the day.  I assigned this over to you, pull down my stuff from today and if you can fix it commit and close this issue.  Otherwise I will look at it tomorrow morning.  Thanks Patrick!

**Comment by thehabes** [comment]
Still working on this and struggling a bit.  I am 4 hours into it today, may abandon soon.

**Comment by thehabes** [comment]
Possibly fixed, needs testing
