### ISSUE TITLE
Project Export (PDF)

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#72]
Users cannot export their transcriptions as PDF.  It loads a new window saying "Failed to load PDF document".

**Comment by cubap** [comment]
feh. This works on the live TPEN, so I believe it is an issue like the mailer with one of the libraries that are loaded on the server. The pdf export was a bear for John Deering and is probably out of date now anyway.

Soooo I think it will just work when we move it. The long term is a rip and replace or just deprecating it and letting people print to pdf from the HTML export (which I think is a more flexible option anyway).

On the other hand, if there is an obvious error, it might be "fixable" but I'm guessing it is an error like "unable to load font-jax.Writer.jar" or something silly.

**Comment by thehabes** [comment]
Works on prod.
