### ISSUE TITLE
exported.jsp linebreak string

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#75]
pagebreak string always shows whether or not you check the box to "Use linebreak string in exported document" before exporting

**Comment by cubap** [comment]
*linebreak, not pagebreak

**Comment by cubap** [comment]
hrm. I'm seeing that it never shows, even when I check it. I'll look more.

**Comment by thehabes** [comment]
You are right.  Somehow I convinced myself that checkbox controlled the (pagebreak) string at the bottom of the page boxes in the HTML export.  Dumb.

Focusing on the fact its supposed to be a linebreak string, it never shows up.  I will relabel this.
