### ISSUE TITLE
Restore Keyboard shortcuts

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#76]
The help has disappeared in this version... maybe that's okay, but the others are needed.

These are useful and should be easy to implement:

```
CTRL + 1-9:
Insert the corresponding special character at the cursor location.
CTRL + HOME:
Quickly jump to the first line of the current page.
ALT + arrows:
Move up and down through lines of transcription with the keyboard arrow keys.
ALT + CTRL:
Hold both to use the peek-zoom, which scales the bounded area to fit your screen and increases the quality of the image, if possible.
```

These are already in this version, I believe

```
ESC:
Close any open tool and return to fullscreen transcription.
TAB:
Move forward through lines of transcription. Reverse with SHIFT + TAB.
+ or - while magnifying:
Each keystroke will adjust the magnification of the tool by .4x to fine tune the image result.
```

These have other buttons or deprecated functionality and may not be needed now

```
ALT:
Hold to adjust the interface. Slide the main workspace up and down to see more of the manuscript;
move the manuscript image freely behind the main workspace; or
resize the bookmark bounding box to precisely bound an odd or skewed line.
CTRL:
Hold to get a better view of the important parts of your manuscript. The bookmark bounding box, location flag, and bug report form will all fade out and let you see the manuscript or tool behind it.
F1:
On the transcription screen, pulls up the application help.
```

**Comment by thehabes** [comment]
From a cursory glance, the ALT + CTRL is the only one that will take any time.  The rest are easy to implement.

Those **are** already in the current version, hooray.

These have buttons or UI controls now, you are correct they are deprecated.

**Comment by Domhnall101** [comment]
need to add a pop up cheat sheet for aNY SHORTCUTS ADDED

**Comment by cubap** [comment]
I used a library on rerum that may be the easiest to implement.

sent mobilly; please excuse any errors.

**Comment by thehabes** [comment]
Tested and Confirmed:

CTRL + 1-9:
Insert the corresponding special character at the cursor location.

CTRL + HOME:
Quickly jump to the first line of the current page.

ALT + up and down arrows:
Move up and down through lines of transcription with the keyboard arrow keys.

ALT + left and right arrows:
Bump the currently selected line left or right (positional change, not size)

ESC:
Close any open tool and return to fullscreen transcription.

Tab or Enter:
When the text area is highlighted, this moves you to the next line.  

Shift + Tab:
When the text area is highlighted, this moves you to the previous line.

Mousewheel up or +:
When magnifying, this increases magnification

Moustwheel down or -:
When magnifying, this decreases magnification.

**Comment by thehabes** [comment]
Need to make/confirm the help popup before closing this.

**Comment by thehabes** [comment]
commit 1087ebb
