### ISSUE TITLE
Annotation Export

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#81]
The annotations lines that are in the export are the lines from the SQL database.  We need to be getting the lines out of Mongo.

It is possible to export a project that only has its lines in SQL...

**Comment by thehabes** [comment]
For this, it looks like there are a lot of methods in Transcription.java that are used to get user transcriptions.

 public static Transcription[] getPersonalTranscriptions(int UID, int folioNumber)
 public static boolean projectHasTranscriptions(int projectID, int folioNumber)
 public static Transcription[] getProjectTranscriptions(int projectID, int folioNumber)
 public static int getNumberOfTranscribedLines()

The pages that use these methods are
Folio.java
Project.java
exported.jsp
compare.jsp
exportUI.jsp
reports.jsp

For our immediate purposes for the export, we need to write a new projectHasTranscriptions and getProjectTranscriptions.  Ultimately, we may need a new Transcription.java or should overhaul what's there because it all looks to the SQL.

**Comment by cubap** [comment]
You may be able to use the check you have when loading a project to see if there are annotations in the store and to copy them over if not. We can probably just step around the existing methods (or fail through to them) for the purposes of exporting.

**Comment by thehabes** [comment]
Edited the Transcription base object and export UI.jsp.  I have done a new 'getProjectTranscriptions' that looks to the store for the annotation list of each canvas, then pulls the text of each line out and puts it to one document.  The supplementary functions have not been updated to detect against this new transcription object set, but those should take much less time now that the main chunk is done.  See the annotation_export branch for details.

**Comment by thehabes** [comment]
Merged branch with master, continuing on this now.

**Comment by thehabes** [comment]
When dong the HTML export option, I can get the transcription from the annotation store.  The line/column designation and UI all look correct, I believe this was successful.

However, the download option is an entire different piece and uses an entirely different Java.  Instead of using the Transcription object, it uses the Manuscript object.  The same custom functionality I did for the Transcription.java will have to be done in Manuscript.java as well.  

In Manuscript.java, I need to write a new getPartialDocument() and getFullDocument() function to be used in export.java in conjunction with project.jsp.  This will allow the Download File functionality to use data from JSON transcription line objects from Mongo instead of the SQL line objects out of the transcription table.

**Comment by thehabes** [comment]
preview of export does not build

**Comment by thehabes** [comment]
This should be fixed with database rollback.  Needs testing.

**Comment by thehabes** [comment]
The export all looks good, whether you download or view HTML.  I cannot test the PDF export on the dev server, it would need to be put on prod.  However, we can assume it works because when we tested the old code on prod it worked and there has been no changes to this.
