### ISSUE TITLE
Folio SQL 

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#83]
Scan the folio entries and try to resolve the URL.  If it fails, add that entry to a list so we can see all the folios that are broken.

**Comment by thehabes** [comment]
There is no SQL script that can do this.  SQL can test the validity of a URL but not whether or not it actually resolves.   We will either need to make a little Java or PHP servlet to do this for us.  My tendency is just to build a little Java servlet into TPEN28 that we can re-use for this check later in life.

**Comment by thehabes** [comment]
There is also a set of scripts written by Daniel on the prod server, I could write one to do this and add it to that script collection

**Comment by thehabes** [comment]
successful.  You can hit /folioServlet and it will generate a text file with the report in /home/bhaberbe/sql named folioReport.txt

**Comment by thehabes** [comment]
At present there are 1486129 folio entries and it checks them about a rate of about 2 per second.  This means the algorithm will need to run for about 8 days to generate this report.

**Comment by thehabes** [comment]
I have gotten a fresh copy of the TPEN sql.  I plan to run the FolioReport java file off a different machine that can go uninterrupted for a week to generate a file of bad folios through a local TPEN28 instance or by just running the java file against the local database.

**Comment by thehabes** [comment]
This is running locally on the omeka machine in the office, it should complete by 1/17/16

**Comment by thehabes** [comment]
Needs to be rewritten.  Eventually, the HD did stop over the long weekend and when I woke the computer the process restarted.  This needs to be done on a computer not bound by SLU's rules b/c it will idle.  It would also work if done on a server.

It should be rewritten to write out a line at a time.  I will need a half day to try to rewrite this, but I had a lot of issues when trying to make this write out a line at a time when I first wrote it, so this may take a good chunk of time.

**Comment by cubap** [comment]
This will need to be run on the server because some of the repositories have backdoors just for T-PEN. The alternative would be to not use the direct links, but use the T-PEN proxy, but I think that would attempt to autoparse every image that hasn't been transcribed yet...
