### ISSUE TITLE
Updates Tab reappeared

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#84]
The updates tab came back on index.jsp at TPEN proper, but should be hidden since the articles it links to are not relevant or helpful. While in there, the maintenance flag could probably be hidden, since it is inaccurate for now.

**Comment by cubap** [comment]
Also, the G+ and Blogger badges on the sharebar should be dropped.

**Comment by thehabes** [comment]
Done deal, please test and make sure I did the right thing.
